const characterOracleResults = {
    "oracle-character-name-result": [
        "Akim",
        "Alex",
        "Alexis",
        "Alisa",
        "Althea",
        "Amari",
        "Aparna",
        "Argus",
        "Arnav",
        "Ash",
        "Asha",
        "Astrid",
        "Aurora",
        "Ayako",
        "Azriel",
        "Blake",
        "Brennan",
        "Brianna",
        "Bruna",
        "Bruno",
        "Cassidy",
        "Christa",
        "Cole",
        "Corey",
        "Creed",
        "Derya",
        "Dex",
        "Doran",
        "Echo",
        "Eren",
        "Erim",
        "Esana",
        "Eveline",
        "Faye",
        "Fletcher",
        "Flint",
        "Florian",
        "Gavin",
        "Halia",
        "Ike",
        "Isaac",
        "James",
        "Janya",
        "Jihun",
        "Jorunn",
        "Juliana",
        "Juro",
        "Kaisa",
        "Karthik",
        "Kayla",
        "Kei",
        "Kiana",
        "Kieran",
        "Kierra",
        "Kimora",
        "Kiri",
        "Kirsa",
        "Kwan",
        "Kylar",
        "Landry",
        "Logan",
        "Lowell",
        "Lucas",
        "Curtis",
        "Luna",
        "Lux",
        "Mae",
        "Magnus",
        "Mave",
        "Merrick",
        "Mina",
        "Nashida",
        "Nassar",
        "Ostara",
        "Qasira",
        "Quinn",
        "Ragnar",
        "Raven",
        "Ria",
        "Rokuro",
        "Roland",
        "Rowena",
        "Sage",
        "Saren",
        "Annora",
        "Severinus",
        "Shen",
        "Talia",
        "Tomiko",
        "Ulan",
        "Valda",
        "Venri",
        "Vesper",
        "Vuldar",
        "William",
        "Yelena",
        "Zakia",
        "Zari",
        "Zephyr",
        "Zoya",
    ],
    "oracle-character-name-lastname-result":  [
        "Kuzmin",
        "Durant",
        "Jefferies",
        "Velez",
        "Lontoc",
        "Wade",
        "Kade",
        "Thorn",
        "Khosla",
        "Hendrix",
        "Okiro",
        "Ripley",
        "Talin",
        "Jin",
        "Finn",
        "Solas",
        "Quint",
        "Keelan",
        "Silva",
        "Valk",
        "O'Brien",
        "Ruiz",
        "Stallard",
        "Mackenson",
        "Jensen",
        "Sakir",
        "Tolari",
        "Kain",
        "Carr",
        "Valenus",
        "Kaan",
        "Taylan",
        "Legrand",
        "Jemison",
        "Arden",
        "Sayer",
        "Kai",
        "Slater",
        "Edris",
        "Sutton",
        "Savarin",
        "Bridger",
        "Mital",
        "Shin",
        "Nadir",
        "Santos",
        "Mihara",
        "Buhari",
        "Salvi",
        "Adler",
        "Takara",
        "Shelton",
        "Vandu",
        "Vega",
        "Zhang",
        "Savela",
        "Hawking",
        "Jen",
        "Hobbs",
        "Holland",
        "Silvius",
        "Freeman",
        "Barbosa",
        "Winter",
        "Hammond",
        "Archer",
        "Barlowe",
        "Shepherd",
        "Griffin",
        "Frost",
        "Quon",
        "Malek",
        "Murad",
        "Becker",
        "Ammar",
        "Braddock",
        "Blackstone",
        "Hadley",
        "Farin",
        "Kobayashi",
        "Duval",
        "Hunter",
        "Beckett",
        "Dykstra",
        "Gray",
        "Sedano",
        "Bai",
        "Booker",
        "Sato",
        "Vayan",
        "Bond",
        "Stark",
        "Stirling",
        "Wolfe",
        "O'Niel",
        "Petrov",
        "Nazari",
        "Darwin",
        "Pearson",
        "Volkov",
    ],
    "oracle-character-callsign-result": [
        "Albatross",
        "Angler",
        "Anvil",
        "Badger",
        "Bandit",
        "Bash",
        "Basilisk",
        "Bingo",
        "Blackbird",
        "Blade",
        "Bloodshot",
        "Bluewing",
        "Bonfire",
        "Book",
        "Breaker",
        "Brick",
        "Buzz",
        "Buzzard",
        "Centurion",
        "Chimera",
        "Circuit",
        "Clank",
        "Cleric",
        "Crash",
        "Cutter",
        "Cutthroat",
        "Cypher",
        "Dagger",
        "Dancer",
        "Dash",
        "Deadeye",
        "Deuce",
        "Failsafe",
        "Farseer",
        "Fidget",
        "Firestarter",
        "Fixer",
        "Flatline",
        "Ghost",
        "Grudge",
        "Gutshot",
        "Harrow",
        "Havoc",
        "Hellhound",
        "Hellion",
        "Hex",
        "Hush",
        "Ironclad",
        "Jackal",
        "Jackpot",
        "Jester",
        "Link",
        "Longshot",
        "Mainframe",
        "Mantis",
        "Mimic",
        "Mole",
        "Monarch",
        "Mongoose",
        "Nails",
        "Ogre",
        "Omega",
        "Overload",
        "Packrat",
        "Paladin",
        "Phantom",
        "Phoenix",
        "Pyro",
        "Quickdraw",
        "Razor",
        "Rogue",
        "Rook",
        "Rover",
        "Scout",
        "Shadow",
        "Shark",
        "Shutdown",
        "Slack",
        "Slash",
        "Snipe",
        "Spider",
        "Splinter",
        "Static",
        "Stinger",
        "Straggler",
        "Swindle",
        "Tinker",
        "Touchdown",
        "Tycoon",
        "Vagabond",
        "Valkyrie",
        "Vanguard",
        "Vertigo",
        "Warden",
        "Watchdog",
        "Wayfinder",
        "Whisper",
        "Wraith",
        "Wrongway",
        "Zephyr",
    ],
    "oracle-character-look-result": [
        "Accented",
        "Accompanied",
        "Adorned",
        "Aged",
        "Alluring",
        "Armed",
        "Armored",
        "Athletic",
        "Attractive",
        "Augmented",
        "Concealed",
        "Distracted",
        "Eccentric",
        "Energetic",
        "Flashy",
        "Graceful",
        "Grim",
        "Haggard",
        "Ill-equipped",
        "Imposing",
        "Large",
        "Mutated",
        "Plain",
        "Poised",
        "Scarred",
        "Scruffy",
        "Shifty",
        "Sickly",
        "Slight",
        "Swaggering",
        "Tattooed",
        "Threatened",
        "Uncanny",
        "Visibly disabled",
        "Weathered",
        "Well-equipped",
        "Wiry",
        "Wounded",
        "Youthful",
    ],
    "oracle-character-disposition-result": [
        "Helpful",
        "Friendly",
        "Cooperative",
        "Curious",
        "Indifferent",
        "Suspicious",
        "Wanting",
        "Desperate",
        "Demanding",
        "Unfriendly",
        "Threatening",
        "Hostile",
    ],
    "oracle-character-clothing-result": [
        "Antique",
        "Battle-scarred",
        "Scavenged",
        "Blaster-burned",
        "Ceremonial",
        "Dated",
        "Metallic",
        "Eccentric",
        "Elegant",
        "Decaled",
        "Exotic",
        "Fashionable",
        "Flamboyant",
        "Flight-ready",
        "Formal",
        "Frayed",
        "Shiny",
        "Hooded",
        "Grimy",
        "Mix-match",
        "Lacey",
        "Pressurized",
        "Oil-stained",
        "Ostentatious",
        "Oversized",
        "Patched",
        "Patterned",
        "Holographic",
        "Practical",
        "Armored",
        "Symbolic",
        "Singed",
        "Tasteless",
        "Undersized",
        "Spice-stained",
        "Worn out",
    ],
    "oracle-character-profession-background-result": [
        "Agent",
        "Artisan",
        "Assassin",
        "Bounty Hunter",
        "Courier",
        "Crew",
        "Criminal",
        "Cultist",
        "Diplomat",
        "Engineer",
        "Entertainer",
        "Explorer",
        "Farmer",
        "Fugitive",
        "Guard",
        "Guide",
        "Healer",
        "Historian",
        "Hunter",
        "Investigator",
        "Laborer",
        "Lawkeeper",
        "Leader",
        "Mercenary",
        "Merchant",
        "Miner",
        "Mystic",
        "Navigator",
        "Outcast",
        "Pilgrim",
        "Pilot",
        "Pirate",
        "Preacher",
        "Prophet",
        "Raider",
        "Researcher",
        "Scavenger",
        "Scholar",
        "Scout",
        "Shipwright",
        "Smuggler",
        "Soldier",
        "Spacer",
        "Technician",
        "Thief",
    ],
    "oracle-character-revealed-aspect-result": [
        "Addicted",
        "Adventurous",
        "Afflicted",
        "Aggressive",
        "Ambitious",
        "Angry",
        "Anxious",
        "Apathetic",
        "Bitter",
        "Boastful",
        "Boisterous",
        "Bold",
        "Brave",
        "Careless",
        "Cautious",
        "Charismatic",
        "Clever",
        "Conceited",
        "Confident",
        "Confused",
        "Connected",
        "Corrupted",
        "Cowardly",
        "Creative",
        "Critical",
        "Cruel",
        "Cunning",
        "Dangerous",
        "Deceitful",
        "Defiant",
        "Determined",
        "Disabled",
        "Doomed",
        "Driven",
        "Dying",
        "Envious",
        "Experienced",
        "Faithful",
        "Generous",
        "Gifted",
        "Greedy",
        "Grief-stricken",
        "Handy",
        "Hardhearted",
        "Haunted",
        "Honorable",
        "Hot-tempered",
        "Impulsive",
        "Incompetent",
        "Independent",
        "Infamous",
        "Influential",
        "Insensitive",
        "Insightful",
        "Intelligent",
        "Intolerant",
        "Ironsworn",
        "Kind",
        "Law-abiding",
        "Lonely",
        "Loving",
        "Loyal",
        "Manipulative",
        "Oblivious",
        "Obsessed",
        "Oppressed",
        "Passive",
        "Powerful",
        "Proud",
        "Quiet",
        "Quirky",
        "Rebellious",
        "Reclusive",
        "Relaxed",
        "Remorseful",
        "Resourceful",
        "Secretive",
        "Selfish",
        "Sociable",
        "Stealthy",
        "Stern",
        "Stingy",
        "Stoic",
        "Strong",
        "Stubborn",
        "Successful",
        "Suspicious",
        "Talented",
        "Technical",
        "Timid",
        "Tolerant",
        "Tough",
        "Vengeful",
        "Violent",
        "Wary",
        "Watchful",
        "Weak",
        "Weary",
        "Wild",
        "Wise",
    ],
    "oracle-character-gender-result": [
        "Male",
        "Male",
        "Male",
        "Male",
        "Female",
        "Female",
        "Female",
        "Female",
        "Androgyne",
        "Androgyne",
        "Agender",
    ],
    "oracle-character-goal-result": [
        "Avenge a wrong",
        "Build a home",
        "Build a relationship",
        "Claim a resource",
        "Collect a debt",
        "Craft an object",
        "Cure an ill",
        "Defeat a rival",
        "Defend a person",
        "Defend a place",
        "Discover a truth",
        "End a conflict",
        "Escape a captor",
        "Fight injustice",
        "Find a person",
        "Forge an alliance",
        "Gain knowledge",
        "Gain riches",
        "Maintain order",
        "Make an agreement",
        "Obtain an object",
        "Pay a debt",
        "Protect a lifeform",
        "Protect a secret",
        "Prove worthiness",
        "Rebel against power",
        "Refute a falsehood",
        "Repair a technology",
        "Resolve a dispute",
        "Restore a relationship",
        "Sabotage a technology",
        "Secure a resource",
        "Seek redemption",
        "Seize power",
        "Solve a mystery",
        "Spread faith",
        "Travel to a place",
        "Undermine a relationship",
    ],

  "oracle-known-creature-result": [
    "<a href=\"https://starwars.fandom.com/wiki/Rancor\" target=\"_blank\">Rancor</a>",
  ],

  "oracle-creature-environment-result": [
    "Space", 
    "Interior", 
    "Interior", 
    "Land", 
    "Land", 
    "Land", 
    "Land", 
    "Land", 
    "Land", 
    "Liquid", 
    "Liquid", 
    "Liquid", 
    "Liquid", 
    "Air", 
    "Air", 
    "Air", 
  ],

  "oracle-creature-scale-result": [
    "Minuscule (bug-sized)", 
    "Tiny (rodent-sized)", 
    "Tiny (rodent-sized)", 
    "Tiny (rodent-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Small (dog-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Medium (person-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Large (vehicle-sized)", 
    "Huge (whale-sized)", 
    "Huge (whale-sized)", 
    "Huge (whale-sized)", 
    "Huge (whale-sized)", 
    "Titanic (hill-sized)", 
    "Colossal (mountain-sized)", 
    "Vast (planet-sized)", 
  ],

  "oracle-creature-basicform-result": [
    "Amoeba / pseudopods", 
    "Amorphous / elemental", 
    "Avian / winged", 
    "Beast / mammal", 
    "Crustacean / shelled", 
    "Fish / torpedo-shaped", 
    "Humanoid / bipedal", 
    "Insectoid / exoskeletal", 
    "Jellyfish / gasbag", 
    "Lizard / reptilian", 
    "Octopoid / tentacled", 
    "Plant / fungus", 
    "Ray / flat-bodied", 
    "Snake / eel", 
    "Spider / web-weaver", 
    "Starfish / symmetrical", 
    "Worm / slug / larva", 
  ],

  "oracle-creature-firstlook-result": [
    "Antennae or sensory organs", 
    "Armored", 
    "Beautiful", 
    "Biotech", 
    "Bony or gaunt", 
    "Brutish or muscled", 
    "Camouflaged", 
    "Claws or talons", 
    "Compound eyes", 
    "Comprised of many creatures", 
    "Corrupted", 
    "Crystalline", 
    "Dead or undead", 
    "Distinctive markings", 
    "Distinctive smell", 
    "Distinctive sound", 
    "Dripping mucus", 
    "Elongated Neck", 
    "Energy emissions", 
    "Extra limbs", 
    "Faceless or inexpressive", 
    "Fangs or rows of teeth", 
    "Feathered", 
    "Fungal growth", 
    "Fur, hair, or filaments", 
    "Graceful", 
    "Hideous", 
    "Hooded or crested", 
    "Immobile or trapped", 
    "Injured or scarred", 
    "Iridescent", 
    "Long-limbed", 
    "Luminescent", 
    "Mandibles or pincers", 
    "Many-eyed", 
    "Mineral or metallic", 
    "Multi-jointed", 
    "Multi-segmented body", 
    "Ornamented or colorful", 
    "Oversized mouth", 
    "Prominent tail", 
    "Prominent wings or fins", 
    "Ridges or plates", 
    "Scaled", 
    "Single eye or oversized eyes", 
    "Spikes or spines", 
    "Stinger or barbs", 
    "Tentacles or tendrils", 
    "Translucent", 
    "Visible symbiote", 
  ],

  "oracle-creature-behavior-result": [
    "Ambusher", 
    "Apex predator", 
    "Builder", 
    "Camouflager", 
    "Forager", 
    "Grazer", 
    "Herder", 
    "Hibernator", 
    "Hoarder", 
    "Hunter", 
    "Lurer", 
    "Migratory", 
    "Mimic", 
    "Nester", 
    "Pack hunter", 
    "Prey", 
    "Protector", 
    "Scavenger", 
    "Tracker", 
    "Trapper", 
  ],

  "oracle-creature-revealedaspect-result": [
    "Alternative environment", 
    "Alternative movement", 
    "Alternative senses", 
    "Burrower", 
    "Chameleon", 
    "Clever", 
    "Consumes energy", 
    "Consumes inorganic matter", 
    "Controlled or puppeteered", 
    "Controls lesser creatures", 
    "Corrosive excretion", 
    "Crusher or constrictor", 
    "Egg sac or carried offspring", 
    "Electric shock", 
    "Electromagnetic pulse", 
    "Energy breath", 
    "Energy manipulation", 
    "Engineered biology", 
    "Enhanced senses", 
    "Enhanced strength", 
    "Entangling secretion", 
    "Extradimensional", 
    "Hallucinogen secretion", 
    "Hidden symbiote", 
    "Hive mind", 
    "Illusionary", 
    "Infectious", 
    "Infested with parasites", 
    "Intimidating threat display", 
    "Limited sense", 
    "Magnetic", 
    "Mental influence or control", 
    "Metamorphic", 
    "Noxious cloud or spores", 
    "Paralytic toxin", 
    "Parasitic", 
    "Pheromones", 
    "Poisonous", 
    "Powerful bite", 
    "Proboscis or inner jaw", 
    "Projectile attack", 
    "Radioactive", 
    "Regeneration", 
    "Replication", 
    "Sacrificial defense", 
    "Shapechanger", 
    "Telekinetic", 
    "Teleportation", 
    "Territorial", 
    "Toxic spew", 
  ],

  "oracle-known-species-result": [
    "<a href=\"https://starwars.fandom.com/wiki/Duros\" target=\"_blank\">Duros</a>",
  ],

  "oracle-species-name-result": [
    [
        "Bo",
        "Cer",
        "Du",
        "Hu",
        "Ith",
        "Kel",
        "Mir",
        "Mon",
        "Nau",
        "Sul",
        "Ro",
        "To",
        "Tran",
        "Twi",
        "Woo",
        "Za",
    ],
    [
        "", "", "", "", "", "", 
        " ", " ",
        "'", "'", "'", 
        "or",
        "ia",
        "cal",
        "to",
        "lus",
        "gru",
        "do",
        "di",
        "shi",
    ],
    [
        "than",
        "ean",
        "ros",
        "dan",
        "ian",
        "dor",
        "lan",
        "ari",
        "tan",
        "an",
        "ta",
        "shan",
        "lek",
        "brak",
    ],
  ],

  "oracle-species-traits-result": [
     [
        "Short Biped Humanoid, ",
        "Short Biped Humanoid, ",
        "Short Biped Humanoid, ",
        "Medium Biped Humanoid, ",
        "Medium Biped Humanoid, ",
        "Medium Biped Humanoid, ",
        "Medium Biped Humanoid, ",
        "Medium Biped Humanoid, ",
        "Tall Biped Humanoid, ",
        "Tall Biped Humanoid, ",
        "Quadruped Humanoid, ",
     ],
     [
        "Red ",
        "Green ",
        "Blue ",
        "Yellow ",
        "Orange ",
        "Pink ",
        "Turquoise ",
        "White ",
        "Grey ",
        "Translucent ",
        "Black ",
        "Dark ",
        "Brown ",
        "Teal ",
        "Cyan ",
        "Lavender ",
        "Rose ", 
        "Coral ",
        "Scarlet ",
        "Crimson ",
        "Azure ",
        "Amber ",
        "Gold ",
        "Olive ",
     ],
     [
        "Colored ",
        "Tinted ",
     ],
     [
        "Skin, ",
        "Skin, ",
        "Skin, ",
        "Skin, ",
        "Skin, ",
        "Fur, ",
        "Fur, ",
        "Fur, ",
        "Scaly Skin, ",
        "Scaly Skin, ",
        "Hide, ",
        "Carapace, ",
     ],
     [
        "Antennae",
        "Bulbous Eyes",
        "Many Eyes",
        "Single Eye",
        "Lipless Mouth",
        "Noseless Face",
        "Four Arms",
        "Pointy Ears",
        "Small Horns",
        "Large Horns",
        "Short Tendrils instead of Hair",
        "Curved, Elongated Neck",
        "Elongated Snout",
        "Abundant Facial Hair",
        "Corpulent Frame",
        "Long flexible appendages instead of Hair",
        "Tendrils",
        "Clawed Fingers",
     ],
  ],
    
};
export default characterOracleResults;