const miscOracleResults = {
    "oracle-combat-action-result": [
        "Block a path or cut off an objective",
        "Cause reckless damage",
        "Change weapons or tactics",
        "Compel a surrender or concession",
        "Coordinate with allies",
        "Corner, trap, or entangle",
        "Counter or reflect an attack",
        "Create a distraction",
        "Destroy something or render it useless",
        "Fall back or stand off",
        "Hide or sneak",
        "Intimidate, taunt, or frighten",
        "Leverage the advantage of a weapon or ability",
        "Leverage the terrain or surroundings",
        "Lure into a vulnerable position",
        "Make a cautious or probing attack",
        "Make a ferocious or powerful attack",
        "Make a precise or careful attack",
        "Make a sacrificial attack",
        "Make an indirect attack",
        "Move in close or grapple",
        "Nullify a system, device, or weapon",
        "Overrun a position",
        "Perform a feint or trick",
        "Press an advantage",
        "Provoke a careless response",
        "Ready a decisive action",
        "Shift the fight to a new area",
        "Summon aid or reinforcements",
        "Take cover or bolster defenses",
        "Use an unexpected weapon or ability",
        "Weaken defenses",
    ],

};
export default miscOracleResults;