const spaceOracleResults = {
  "oracle-known-planet-result": [
    "<a href=\"https://starwars.fandom.com/wiki/Kamino\" target=\"_blank\">Kamino</a>",
  ],

  "oracle-planet-type-result": [
    "<a href=\"/oracles/planet-oracles#vital-world\">VITAL WORLD</a>: This diverse, lifebearing planet might provide some small measure of hope.",
    "<a href=\"/oracles/planet-oracles#vital-world\">VITAL WORLD</a>: This diverse, lifebearing planet might provide some small measure of hope.",
    "<a href=\"/oracles/planet-oracles#vital-world\">VITAL WORLD</a>: This diverse, lifebearing planet might provide some small measure of hope.",
    "<a href=\"/oracles/planet-oracles#vital-world\">VITAL WORLD</a>: This diverse, lifebearing planet might provide some small measure of hope.",
    "<a href=\"/oracles/planet-oracles#vital-world\">VITAL WORLD</a>: This diverse, lifebearing planet might provide some small measure of hope.",
    "<a href=\"/oracles/planet-oracles#ocean-world\">OCEAN WORLD</a>: A planet completely or mostly covered by a boundless ocean.",
    "<a href=\"/oracles/planet-oracles#ocean-world\">OCEAN WORLD</a>: A planet completely or mostly covered by a boundless ocean.",
    "<a href=\"/oracles/planet-oracles#ocean-world\">OCEAN WORLD</a>: A planet completely or mostly covered by a boundless ocean.",
    "<a href=\"/oracles/planet-oracles#rocky-world\">ROCKY WORLD</a>: A rugged planet scarred by eons of destructive asteroid impacts.",
    "<a href=\"/oracles/planet-oracles#rocky-world\">ROCKY WORLD</a>: A rugged planet scarred by eons of destructive asteroid impacts.",
    "<a href=\"/oracles/planet-oracles#rocky-world\">ROCKY WORLD</a>: A rugged planet scarred by eons of destructive asteroid impacts.",
    "<a href=\"/oracles/planet-oracles#rocky-world\">ROCKY WORLD</a>: A rugged planet scarred by eons of destructive asteroid impacts.",
    "<a href=\"/oracles/planet-oracles#desert-world\">DESERT WORLD</a>: A pitiless planet of searing heat, blowing sand, and sunbaked rock.",
    "<a href=\"/oracles/planet-oracles#desert-world\">DESERT WORLD</a>: A pitiless planet of searing heat, blowing sand, and sunbaked rock.",
    "<a href=\"/oracles/planet-oracles#desert-world\">DESERT WORLD</a>: A pitiless planet of searing heat, blowing sand, and sunbaked rock.",
    "<a href=\"/oracles/planet-oracles#desert-world\">DESERT WORLD</a>: A pitiless planet of searing heat, blowing sand, and sunbaked rock.",
    "<a href=\"/oracles/planet-oracles#jungle-world\">JUNGLE WORLD</a>: A humid, rain-soaked planet which keeps its secrets under a thick canopy of vegetation.",
    "<a href=\"/oracles/planet-oracles#jungle-world\">JUNGLE WORLD</a>: A humid, rain-soaked planet which keeps its secrets under a thick canopy of vegetation.",
    "<a href=\"/oracles/planet-oracles#jungle-world\">JUNGLE WORLD</a>: A humid, rain-soaked planet which keeps its secrets under a thick canopy of vegetation.",
    "<a href=\"/oracles/planet-oracles#jungle-world\">JUNGLE WORLD</a>: A humid, rain-soaked planet which keeps its secrets under a thick canopy of vegetation.",
    "<a href=\"/oracles/planet-oracles#ice-world\">ICE WORLD</a>: A rugged, frozen world—locked in an unending winter.",
    "<a href=\"/oracles/planet-oracles#ice-world\">ICE WORLD</a>: A rugged, frozen world—locked in an unending winter.",
    "<a href=\"/oracles/planet-oracles#ice-world\">ICE WORLD</a>: A rugged, frozen world—locked in an unending winter.",
    "<a href=\"/oracles/planet-oracles#furnace-world\">FURNACE WORLD</a>: A planet with relentless volcanic activity, wreathed in fire and ash.",
    "<a href=\"/oracles/planet-oracles#furnace-world\">FURNACE WORLD</a>: A planet with relentless volcanic activity, wreathed in fire and ash.",
    "<a href=\"/oracles/planet-oracles#jovian-world\">JOVIAN WORLD</a>: A massive planet with vast layers of dense gasses surrounding a small rocky core.",
    "<a href=\"/oracles/planet-oracles#tainted-world\">TAINTED WORLD</a>: A foul planet wracked by a poisonous climate and virulent growths.",
    "<a href=\"/oracles/planet-oracles#shattered-world\">SHATTERED WORLD</a>: A world sundered by cataclysmic destruction.",
    "<a href=\"/oracles/planet-oracles#grave-world\">GRAVE WORLD</a>: A once-thriving world—now a grim monument to a fallen civilization.",
  ],

  "oracle-planet-name-result": [
    [
      "Æ",
      "Arc",
      "A",
      "Ab",
      "Ag",
      "At",
      "Am",
      "Amon",
      "An",
      "Ant",
      "Aer",
      "Aeria",
      "Ar",
      "Aria",
      "Atar",
      "Astar",
      "Ana",
      "Av",
      "Ba",
      "Ban",
      "Bant",
      "Bar",
      "Be",
      "Bet",
      "Bi",
      "Bro",
      "Bo",
      "Bon",
      "Brum",
      "B’",
      "Ca",
      "Camp",
      "Car",
      "Carr",
      "Ce",
      "Cer",
      "Ci",
      "Clo",
      "Chur",
      "Cold",
      "Con",
      "Coper",
      "Corr",
      "Cu",
      "Cy",
      "C’",
      "Da",
      "Dark",
      "De",
      "Del",
      "Deep",
      "Dep",
      "Der",
      "Dikar",
      "Du",
      "Dur",
      "Dun",
      "E",
      "Ea",
      "El",
      "Er",
      "Exo",
      "Far",
      "Fox",
      "Fog",
      "Fon",
      "Fur",
      "Fun",
      "Fung",
      "Galad",
      "Gan",
      "Gunt",
      "Gren",
      "H",
      "Hub",
      "Har",
      "Haar",
      "Hark",
      "Hel",
      "Hon",
      "Hed",
      "Ib",
      "Ich",
      "Ian",
      "Int",
      "Iv",
      "Jan",
      "Ko",
      "K'",
      "Kaan",
      "Khan",
      "Kne",
      "Ken",
      "Ket",
      "Kep",
      "Ku",
      "Klin",
      "Lad",
      "Leg",
      "Lig",
      "Lo",
      "Lo",
      "Lone",
      "Long",
      "L'",
      "Ll'",
      "Majest",
      "Maz",
      "Mer",
      "Merg",
      "Merc",
      "Miran",
      "Mun",
      "Nar",
      "Nan",
      "Nad",
      "Nas",
      "Night",
      "Nir",
      "Nit",
      "Nib",
      "Non",
      "No",
      "Ob",
      "Ox",
      "Out",
      "Ov",
      "Oz",
      "Pa",
      "Pat",
      "Pap",
      "Pan",
      "Pert",
      "Plane",
      "Plu",
      "Plo",
      "Pro",
      "Pra",
      "Pran",
      "Por",
      "Pool",
      "Pling",
      "Py",
      "Pyro",
      "Rem",
      "Ran",
      "Rus",
      "Sai",
      "S'",
      "So'",
      "Sat",
      "Sen",
      "Sev",
      "Shan",
      "Shandak",
      "Siden",
      "Sizen",
      "Sot",
      "Sop",
      "Sot Ank",
      "Sot Lo",
      "Son",
      "Scar",
      "Steep",
      "Suil",
      "Sul",
      "Sum",
      "Sun",
      "Sva",
      "Syn",
      "T",
      "Tac",
      "Tad",
      "Taf",
      "Tag",
      "Tai",
      "Tal",
      "Talm",
      "Tam",
      "Tar",
      "Tas",
      "Tash",
      "Tav",
      "Tax",
      "Tat",
      "Tap",
      "Tep",
      "Tha",
      "Than",
      "Than Dok",
      "Thry",
      "Trel",
      "Treep",
      "Ter Threp",
      "Tol",
      "Ur",
      "Uran",
      "Um",
      "Vab",
      "Vad",
      "Vak",
      "Vak",
      "Vam",
      "Vad",
      "Ven",
      "Ves",
      "Ver",
      "Vis",
      "Viv",
      "Vul",
      "Vop",
      "War",
      "Won",
      "Wo",
      "Won",
      "What",
      "Whim",
      "Wim",
      "Win",
      "War",
      "Wad",
      "Wan",
      "Wun",
      "X'",
      "Xe'",
      "Xen",
      "Xio",
      "Xy",
      "Zing",
      "Zed",
      "Zer",
      "Zem",
      "Zeng",
    ],
    [
      "-o",
      "acalla",
      "addon",
      "adon",
      "acan",
      "aroid",
      "anbula",
      "angolia",
      "angalia",
      "ankor",
      "aldi",
      "aka",
      "aleko",
      "alis",
      "alla",
      "alos",
      "an",
      "andia",
      "anella",
      "ania",
      "amis",
      "arnia",
      "aran",
      "ara",
      "arth",
      "arius",
      "atoid",
      "avera",
      "budram",
      "budria",
      "burto",
      "borto",
      "bongo",
      "can",
      "cania",
      "cania",
      "caris",
      "cury",
      "chil",
      "chin",
      "chia",
      "chania",
      "con",
      "da",
      "dai",
      "dania",
      "daleko",
      "dalekon",
      "doria",
      "donia",
      "dikar",
      "eko",
      "ella",
      "elos",
      "elius",
      "elerth",
      "elialia",
      "eria",
      "era",
      "enia",
      "enella",
      "erebus",
      "es",
      "esh",
      "eaux",
      "ebus",
      "eus",
      "eran",
      "fall",
      "far",
      "finer",
      "gania",
      "gatis",
      "gill",
      "golia",
      "ian",
      "ion",
      "illian",
      "illa",
      "idian",
      "inax",
      "iman",
      "itas",
      "ius",
      "iza",
      "iru",
      "ix",
      "kail",
      "kien",
      "las",
      "lax",
      "lak",
      "ler",
      "land",
      "lejos",
      "lok",
      "los",
      "lox",
      "lon",
      "miniar",
      "nar",
      "nia",
      "nicus",
      "nor",
      "nt",
      "ntos",
      "oda",
      "oid",
      "oin",
      "ol",
      "omi",
      "on",
      "onine",
      "ong",
      "ongolia",
      "onia",
      "ornia",
      "ornania",
      "opa",
      "opia",
      "opia",
      "olok",
      "os",
      "oros",
      "orox",
      "orkon",
      "ovin",
      "ox",
      "pidor",
      "pid",
      "pod",
      "rax",
      "reus",
      "rock",
      "roid",
      "rog",
      "ryn",
      "sea",
      "shaa",
      "tan",
      "tara",
      "taria",
      "ton",
      "tes",
      "tep",
      "thra",
      "tania",
      "to",
      "tos",
      "tose",
      "tonia",
      "tronia",
      "topia",
      "tos",
      "trock",
      "tropic",
      "tus",
      "udros",
      "ule",
      "um",
      "umi",
      "uram",
      "urn",
      "urrinia",
      "ury",
      "urdan",
      "uria",
      "uridan",
      "uridian",
      "us",
      "utlis",
      "va",
      "vana",
      "vas",
      "vav",
      "vin",
      "vis",
      "viz",
      "za",
      "‘am",
      "‘an",
      "‘us",
      "al",
    ],
    [
      "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
      " Alpha",
      " Beta",
      " Gamma",
      " Kappa",
      " Sigma",
      " Prime",
      " Major",
      " Minor",
      " One",
      " Two",
      " Epsilon",
      " Zeta",
      " Quintus",
      " 1", " 2", " 3", " 4", " 5", " 6", " 7", " 8", " 9", " 10", " 11", " 12",
      " I", " II", " III", " IV", " V", " VI", " VII", " VIII", " IX", " X", " XI", " XII", " XIV", " XV", " XVI",
    ],
  ],

  "oracle-planet-atmosphere-result": [
    "Breathable",
    "Breathable",
    "Breathable",
    "Breathable",
    "Breathable",
    "Breathable",
    "Marginal",
    "Marginal",
    "Marginal",
    "Marginal",
    "Ideal",
    "Ideal",
    "Ideal",
    "None / Thin",
    "Toxic",
    "Corrosive",
  ],

  "oracle-planet-life-result": [
    "None",
    "Extinct",
    "Scarce",
    "Scarce",
    "Scarce",
    "Diverse", 
    "Diverse", 
    "Diverse", 
    "Diverse", 
    "Diverse", 
    "Bountiful",
    "Overrun",
  ],

  "oracle-planetside-peril-result": [
    "Corrupted or mutated lifeform",
    "Signs of a lifeform's power or cunning",
    "Hazardous plant life or malignant spores",
    "Lifeform hunts for prey",
    "Lifeform lairs here",
    "Lifeforms guided by a greater threat",
    "Lifeforms spooked or stampeding",
    "Threatening lifeform draws near",
    "Life is revealed or takes an unexpected form",
    "Blocked or impassible path",
    "Corrosive substance or environment",
    "Disturbing remains or evidence of death",
    "Drastic environmental change",
    "Enemy holds this area",
    "Entangling or engulfing hazard",
    "Equipment fails or malfunctions",
    "Guarded or patrolled path",
    "Led astray",
    "Lost the path",
    "Meteorites fall from the sky",
    "Irradiated area or object",
    "Realization that something was left behind",
    "Seismic or volcanic upheaval",
    "Signs of a lurking or trailing foe",
    "Storm or atmospheric disruption",
    "Toxic or sickening environment",
    "Trap or alarm",
    "Treacherous or arduous path",
    "Troubling visions or apparitions",
    "Visibility hindered by atmospheric effects",
    "Worrying arrival of a ship or vehicle",
    "Wreckage or ruins portend a new threat",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-planetside-opportunity-result": [
    "Clue to a lifeform's nature or vulnerabilities",
    "Friendly interaction with a benign lifeform",
    "Hunting or foraging opportunities are plentiful",
    "Interesting or helpful aspect of benign creatures",
    "Interesting or helpful aspect of local plant life",
    "Encounter reveals unexpected benign lifeforms",
    "Abandoned camp or vehicle",
    "Advance warning of an environmental threat",
    "Clear path through otherwise perilous terrain",
    "Clue offers insight into a current quest or mystery",
    "Clue to the history or nature of this place",
    "Evidence that others have passed this way",
    "Foe reveals themselves or tips their hand",
    "Fortuitous change in the weather or atmosphere",
    "Friendly traveler crosses your path",
    "Helpful resource is in ample supply",
    "Impressive vista offers comfort or inspiration",
    "Interesting artifact or device",
    "Interesting site offers opportunities for exploration",
    "Moment of fellowship or inner peace",
    "Opening to distract, escape, or avoid foes",
    "Opening to get the drop on a foe",
    "Plea for help from a potential benefactor",
    "Refuge offers a place to hide, plan, or recover",
    "Vantage point reveals the lay of the land",
  ],

  "oracle-vital-world-biome-result": [
    "Caves",
    "Cold forest",
    "Fungal",
    "Glacial or snow",
    "Grassland",
    "Islands",
    "Jungle",
    "Mountainous",
    "Ocean",
    "Rocky desert",
    "Sandy desert",
    "Savanna",
    "Shallow seas",
    "Shrubland",
    "Temperate rainforest",
    "Temperate forest",
    "Tundra",
    "Volcanic",
    "Waterways",
    "Wetland",
  ],

  "oracle-vital-world-observed-result": [
    "Complex ring system",
    "Numerous small moons",
    "Dramatic seasonal variation",
    "Unusual day or night cycle",
    "High gravity",
    "Vibrantly colored landscapes",
    "Large moon",
    "Narrow livable band",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-vital-world-feature-result": [
    "Background radiation",
    "Chaotically juxtaposed biomes",
    "Creature boneyards",
    "Creature lairs or watering holes",
    "Crystalline formations",
    "Fierce electrical storms",
    "Floating terrain",
    "Frequent seismic activity",
    "Magnetic disturbances",
    "Scarred or excavated terrain",
    "Signs of an engineered biosphere",
    "Sudden weather fluctuations",
    "Towering geological formations",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-ocean-world-observed-result": [
    "Complex reef systems",
    "Emerging volcanoes",
    "Floating forests",
    "Global hurricanes",
    "Large moon and strong tides",
    "Scattered islands",
    "Semi-frozen oceans",
    "Unusual water color",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-ocean-world-feature-result": [
    "Abyssal trenches",
    "Living islands",
    "Luminescent seas",
    "Roaming icebergs",
    "Shallow-water plains",
    "Subsurface volcanoes",
    "Titanic waves",
    "Undersea air pockets",
    "Undersea caves",
    "Undersea forests",
    "Unrelenting rainfall",
    "Violent currents",
    "Windborne waterspouts",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-rocky-world-observed-result": [
    "Barren plains",
    "Constant asteroid strikes",
    "Dense ring system",
    "Jagged mountains",
    "Massive impact crater",
    "Misshapen form (low gravity)",
    "Perpetual night",
    "Towering plateaus",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-rocky-world-feature-result": [
    "Crystalline formations",
    "Crystalline caves",
    "Exposed mineral deposits",
    "Geometric terrain features",
    "Geothermal vents",
    "Glassy impact craters",
    "Massive dust dunes",
    "Powerful magnetic fields",
    "Rubble-strewn lava fields",
    "Steam-heated caves",
    "Subsurface magma flows",
    "Swirling low-lying gases",
    "Towering rocky spires",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-desert-world-observed-result": [
    "Dry seabeds",
    "Expansive dune seas",
    "Massive canyons",
    "Perpetual daylight",
    "Rugged mountains",
    "Sprawling salt flats",
    "Vast plateaus",
    "Vibrant terrain colors",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-desert-world-feature-result": [
    "Cavernous sinkholes",
    "Engulfing sandstorms",
    "Fleeting rainstorms and flash floods",
    "Flooded grottos",
    "Petrified forest",
    "Rampaging whirlwinds",
    "Scorched glass plains",
    "Severe temperature fluctuations",
    "Sunbaked bones of titanic creatures",
    "Timeworn cliffside caves",
    "Towering rock formations",
    "Violent electrical storms",
    "Windborne metallic sand",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-jungle-world-observed-result": [
    "Cloud-breaching trees",
    "Towering mountains",
    "Expansive rivers or wetlands",
    "Unbroken canopy",
    "Inland seas",
    "Unusual vegetation color",
    "Massive canyons",
    "Persistent cloud cover",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-jungle-world-feature-result": [
    "Bioluminescent flora",
    "Deep river gorges",
    "Extensive exposed root systems",
    "Immense tiered waterfalls",
    "Languid rivers",
    "Low-lying fog",
    "Plunging sinkholes",
    "Scarred clearings",
    "Sinking quagmires",
    "Surging rivers",
    "Torrential rainstorms",
    "Violent electrical storms",
    "Waterlogged caves",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-ice-world-observed-result": [
    "Feeble sunlight",
    "Supersized ice volcano",
    "Frozen oceans",
    "Vibrantly colored ice",
    "Rocky glacial islands",
    "World-spanning ice canyon",
    "Snowbound mountains",
    "Sky-breaching geysers",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-ice-world-feature-result": [
    "Abyssal ice fissures",
    "Blinding snow storms",
    "Clusters of ice spikes",
    "Colossal ice caves",
    "Glistening ice spires",
    "Massive snow drifts",
    "Preserved carcasses",
    "Rocky islands amid icy wastes",
    "Shattered plains of pack ice",
    "Steaming hot springs",
    "Subsurface liquid oceans",
    "Vibrant auroras",
    "Wind-carved ice formations",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-furnace-world-observed-result": [
    "Fiery world-spanning chasms",
    "Glowing rivers of lava",
    "Lightning-wracked ash clouds",
    "Magma seas",
    "Massive supervolcano",
    "Once verdant terrain",
    "Towering mountain ranges",
    "World-spanning fissures",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-furnace-world-feature-result": [
    "Blinding ash storms",
    "Catastrophic earthquakes",
    "Colorful geothermal springs",
    "Intricate volcanic rock formations",
    "Lava tube tunnel networks",
    "Masses of scorched bones",
    "Plains of volcanic glass",
    "Pools of liquid metal",
    "Rocky islands adrift on magma",
    "Roiling clouds of superheated gas",
    "Scalding geysers",
    "Silica or metal storms",
    "Steaming mudflats",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-jovian-world-observed-result": [
    "Complex ring system",
    "Intense gravity well",
    "Numerous moons",
    "Perpetual superstorm",
    "Powerful magnetic field",
    "Severe electrical storms",
    "Superheated atmosphere",
    "Unusual atmospheric colors",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-jovian-world-feature-result": [
    "Clouds of metal particles",
    "Crystalline rains",
    "Floating glaciers",
    "Floating islands",
    "Layer of suspended liquid",
    "Pockets of explosive gases",
    "Powerful vortexes",
    "Radiation fields",
    "Storm-swept rocky debris",
    "Torrential rain",
    "Towering thunderheads",
    "Violent turbulence",
    "Zones of localized atmosphere",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-tainted-world-observed-result": [
    "Expansive fungal plains",
    "Stagnant cloud cover",
    "Fungal forests",
    "Thick, murky atmosphere",
    "Scabrous, infected terrain",
    "Toxic seas",
    "Sky-breaching fungus",
    "Sludge-filled river networks",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-tainted-world-feature-result": [
    "Caustic gas storms",
    "Corrosive, low-lying fog",
    "Fungus-encrusted caves",
    "Gelatinous ponds",
    "Hallucinogenic toxins",
    "Layers of fast-growing lichen",
    "Moldering bones",
    "Mutated flora",
    "Poisonous gas vents",
    "Spore clouds",
    "Terrain marred by fleshy pustules",
    "Toxic rain",
    "Virulent fungal infestations",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-shattered-world-observed-result": [
    "Demolished space fleet",
    "Preserved planetary fragment",
    "Dense ring system",
    "Swirling debris field",
    "Fiery planetary core",
    "Unbroken moon",
    "Geomagnetic storms",
    "Intense solar radiation",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-shattered-world-feature-result": [
    "Broken cities",
    "Colliding fragments",
    "Energy storms",
    "Exposed caverns",
    "Fluctuating gravity",
    "Magnetic disturbances",
    "Molten fissures",
    "Phantom visions of the past",
    "Pocket atmosphere",
    "Residual energy storms",
    "Swirling corrosive gases",
    "Unstable and fracturing terrain",
    "Venting magma",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-grave-world-observed-result": [
    "Broken moon",
    "Perpetual overcast",
    "Cratered surface",
    "Sky-breaching ruins",
    "Dry seabeds",
    "Vast wastelands",
    "Irradiated atmosphere",
    "Orbiting ship graveyard",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-grave-world-feature-result": [
    "Acid pools",
    "Ash dunes",
    "Corrosive rains",
    "Dead forests",
    "Fetid mudflats",
    "Mass graves",
    "Moldering bones",
    "Noxious fog",
    "Radioactive hotspots",
    "Ravaged cities",
    "Scarred battlefields",
    "Ship graveyards",
    "Whispers of the dead",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-settlement-name-result": [
    "Aegis",
    "Altair",
    "Altura",
    "Amity",
    "Apex",
    "Apogee",
    "Argosy",
    "Astra",
    "Aurora",
    "Beacon",
    "Brink",
    "Bulwark",
    "Burnell",
    "Burrow",
    "Concord",
    "Crux",
    "Deadrock",
    "Deception",
    "Elysium",
    "Enigma",
    "Erebus",
    "Eris",
    "Evenfall",
    "Eventide",
    "Farpoint",
    "Felicity",
    "Florin",
    "Forlorn",
    "Forsaken",
    "Freya",
    "Glimmer",
    "Gloam",
    "Hearth",
    "Helia",
    "Hypatia",
    "Hyperion",
    "Janus",
    "Karma",
    "Kepler",
    "Koshiba",
    "Lagrange",
    "Larissa",
    "Lasthope",
    "Lastport",
    "Legacy",
    "Lodestar",
    "Luminus",
    "Lyra",
    "Marrow",
    "Meridian",
    "Moirai",
    "Mudd",
    "Neoma",
    "Nerio",
    "Nova",
    "Nyx",
    "Osseus",
    "Paradox",
    "Paragon",
    "Paxton",
    "Perchance",
    "Pinnacle",
    "Polaris",
    "Portent",
    "Prism",
    "Providence",
    "Purgatory",
    "Rampart",
    "Ramshackle",
    "Redemption",
    "Redhaven",
    "Relic",
    "Reprise",
    "Reverie",
    "Rhiannon",
    "Rockhome",
    "Rust",
    "Sagan",
    "Sanctity",
    "Selena",
    "Sepulcher",
    "Sigil",
    "Silvana",
    "Sirius",
    "Sisyphus",
    "Solitude",
    "Spire",
    "Starfall",
    "Summit",
    "Tranquility",
    "Tyson",
    "Unity",
    "Utopia",
    "Vega",
    "Vesper",
    "Wayward",
    "Welkin",
    "Wellspring",
    "Weyland",
    "Wreck",
  ],

  "oracle-settlement-firstlook-result": [
    "Beautiful architecture",
    "Built from organic materials",
    "Built from random scrap",
    "Built within repurposed ship",
    "Built within terrain or asteroid",
    "Defensible location",
    "Elevated or multi-level construction",
    "Hidden or subsurface location",
    "High-tech construction",
    "Industrial architecture",
    "Intimidating defenses",
    "Moving or transforming",
    "Obvious social stratification",
    "Precarious location",
    "Rustic architecture",
    "Significant structural damage",
    "Sprawling or dispersed structures",
    "Temporary or seasonal location",
    "Toxic or polluted habitat",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-settlement-initialattitude-result": [
    "Welcoming",
    "Welcoming",
    "Welcoming",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Wary",
    "Wary",
    "Wary",
    "Uncooperative",
    "Hostile",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "In battle",
    "Captured",
    "Unresponsive",
    "Destroyed",
  ],

  "oracle-settlement-authority-result": [
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "Ineffectual",
    "Tolerant",
    "Tolerant",
    "Tolerant",
    "Fair",
    "Fair",
    "Fair",
    "Unyielding",
    "Corrupt",
    "Oppressive",
    "Oppressive",
  ],

  "oracle-settlement-projects-result": [
    "Agriculture",
    "Archeology",
    "Automation",
    "Black market",
    "Command",
    "Defense",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmentalism",
    "Evacuation",
    "Expansion",
    "Exploration",
    "Festival",
    "History",
    "Hunting",
    "Manufacturing",
    "Medical",
    "Migration",
    "Mining",
    "Pacifism",
    "Raiding",
    "Research",
    "Salvage",
    "Secrecy",
    "Shipbuilding",
    "Spirituality",
    "Subsistence",
    "Surveillance",
    "Terraforming",
    "Trade",
    "Warfare",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-settlement-trouble-result": [
    "Battle for leadership",
    "Betrayal from within",
    "Caught in the crossfire",
    "Changing environment",
    "Clash of cultures",
    "Dangerous discovery",
    "Depleted supplies",
    "Deprived of a resource",
    "Failing technology",
    "Feuding factions",
    "Ghostly visitations",
    "Hazardous environment",
    "Hostile lifeforms",
    "Impassable route",
    "Impending attack",
    "Impending natural disaster",
    "Invasive organisms",
    "Mounting debt",
    "Mysterious deaths",
    "Overdue delivery",
    "Plagued by sickness",
    "Preyed upon by raiders",
    "Revolt against leadership",
    "Sabotaged technology",
    "Shunned by others",
    "Social strife",
    "Someone is ill or injured",
    "Someone is missing",
    "Stolen technology or object",
    "Strange phenomenon",
    "Toxic waste or pollution",
    "Volatile energy source",
    "Vulnerable lifeforms",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],
};
export default spaceOracleResults;