const spaceOracleResults = {
  "oracle-space-sighting-result": [
    "<a href=\"/oracles/space-oracles#star\">Star</a>",
    "<a href=\"/oracles/space-oracles#celestial-phenomena\">Celestial Phenomena</a>",
    "<a href=\"/oracles/space-oracles#debris-field\">Debris Field</a>",
    "<a href=\"/oracles/planet-oracles\">Planet</a>",
    "<a href=\"/oracles/space-oracles#space-settlements\">Settlement</a>",
    "<a href=\"/oracles/space-oracles#starships\">Starship</a>",
    "<a href=\"/oracles/space-oracles#derelicts\">Derelict</a>",
    "<a href=\"/oracles/character-oracles#creatures\">Creature</a>",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-star-result": [
    "Smoldering Red Star",
    "Smoldering Red Star",
    "Smoldering Red Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Blazing blue star",
    "Blazing blue star",
    "Blazing blue star",
    "White dwarf shining with spectral light",
    "White dwarf shining with spectral light",
    "White dwarf shining with spectral light",
    "Two Red Stars orbiting far from each other",
    "Two Red Stars orbiting far from each other",
    "Two stars in close orbit connected by fiery tendrils of energy",
    "Two stars in close orbit connected by fiery tendrils of energy",
    "Young star incubating in a molecular cloud",
    "Corrupted star radiating with unnatural light",
    "Neutron star surrounded by intense magnetic fields",
    "Hypergiant star generating turbulent solar winds",
    "Artificial star constructed by a long-dead civilization",
    "Unstable star showing signs of impending supernova",

  ],

  "oracle-celestial-phenomena-result": [
    "Large Rogue Asteroid",
    "Comet with a Tail of Ionized Gas",
    "Fiery Energy Storm",
    "Chaotic Meteoroid Storm",
    "Turbulent Gravitational Wave",
    "Dense Nebula Cloud",
    "Small Black Hole",
    "Supermassive Black Hole",
  ],

  "oracle-debris-field-result": [
    "Mineral Asteroids",
    "Frozen Asteroids",
    "Creature boneyard",
    "Metallic Wreckage",
  ],

  "oracle-known-sector-result": [
    "<a href=\"https://starwars.fandom.com/wiki/Koradin_sector\" target=\"_blank\">Koradin Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Aubreeyan_Cluster\" target=\"_blank\">Aubreeyan Cluster</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Bajic_sector\" target=\"_blank\">Bajic Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Bakura_sector\" target=\"_blank\">Bakura Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Barma_sector\" target=\"_blank\">Barma Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cadavine_sector\" target=\"_blank\">Cadavine Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cadavine_sector\" target=\"_blank\">Cadavine Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cassander_sector\" target=\"_blank\">Cassander Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Corbett_sector\" target=\"_blank\">Corbett Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Croynar_sector\" target=\"_blank\">Croynar Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/D%27Aelgoth_sector\" target=\"_blank\">D'Aelgoth Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Dalicron_sector\" target=\"_blank\">Dalicron Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Deratus_Sector\" target=\"_blank\">Deratus Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Elochar_sector\" target=\"_blank\">Elochar Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Elrood_sector\" target=\"_blank\">Elrood Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Fakir_sector\" target=\"_blank\">Fakir Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sector_Four_(Confederacy)\" target=\"_blank\">Sector Four (Confederacy)</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gradilis_sector\" target=\"_blank\">Gradilis Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Moddell_sector\" target=\"_blank\">Moddell Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Zuma_sector\" target=\"_blank\">Zuma Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Terrabe_sector\" target=\"_blank\">Terrabe Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gomar_sector\" target=\"_blank\">Gomar Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Grehollo_sector\" target=\"_blank\">Grehollo Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Guagenian_sector\" target=\"_blank\">Guagenian Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Haldeen_sector\" target=\"_blank\">Haldeen Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Halla_sector\" target=\"_blank\">Halla Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Halthor_sector\" target=\"_blank\">Halthor Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Heterkus_sector\" target=\"_blank\">Heterkus Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Hosnian_sector\" target=\"_blank\">Hosnian Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Humbarine_sector\" target=\"_blank\">Humbarine Sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Juris_sector\" target=\"_blank\">Juris sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Kala_sector\" target=\"_blank\">Kala sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Kligson%27s_Moon%27s_sector\" target=\"_blank\">Kligson's Moon's sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lankor_sector\" target=\"_blank\">Lankor sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Limbala_sector\" target=\"_blank\">Limbala sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lixal_sector\" target=\"_blank\">Lixal sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Mestani_sector\" target=\"_blank\">Mestani sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Morellian_Commonwealth\" target=\"_blank\">Morellian Commonwealth</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Noonian_sector\" target=\"_blank\">Noonian sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Numesira_sector\" target=\"_blank\">Numesira sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Quohag_sector\" target=\"_blank\">Quohag_sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Rayter_sector\" target=\"_blank\">Rayter sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Regani_sector\" target=\"_blank\">Regani sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sector_11_(location)\" target=\"_blank\">Sector 11</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sector_G-38\" target=\"_blank\">Sector G-38</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Tonnis_sector\" target=\"_blank\">Tonnis sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Ugroth%27s_sector\" target=\"_blank\">Ugroth's sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Urce_sector\" target=\"_blank\">Urce sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Valtava_sector\" target=\"_blank\">Valtava sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Yushan_sector\" target=\"_blank\">Yushan sector</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Zebitrope_sector\" target=\"_blank\">Zebitrope sector</a>",
  ],

  "oracle-unknown-sector-result": [
    [
      "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", 
      "Alpha",
      "Beta",
      "Gamma",
      "Ceti",
      "Picon",
      "Delta",
      "Epsilon",
      "Theta",
      "Zeta",
      "Omega",
      "Tau",
      "Nebulon",
      "Far",
      "Deep",
      "Omicron",
      "Sigma",
      "Kappa",
      "Rho",
      "Minor",
      "Major",
      "Greater",
      Math.floor(Math.random() * 300),
    ],
    [
      "Arfell",
      "Aeron",
      "Andromeda",
      "Apius",
      "Aquarius",
      "Ara",
      "Alcor",
      "Algol",
      "Antares",
      "Basri",
      "Behram",
      "Picoris",
      "Boötes",
      "Cancri",
      "Canes Venatici",
      "Canis",
      "Capricorn",
      "Cassiopeia",
      "Castor",
      "Cebus",
      "Centaurus",
      "Ceti",
      "Cetus",
      "Coma Berenices",
      "Corona Borealis",
      "Corot",
      "Cygnus",
      "Cygni",
      "Draco",
      "Eridanus",
      "Eridanus",
      "Fiken",
      "Fornax",
      "Fomalhaut",
      "Gilese",
      "Goddard",
      "Hercules",
      "Herculis",
      "Horologium",
      "Holbrook",
      "Hydra",
      "Hydrus",
      "Leo",
      "Leonis",
      "Libra",
      "Librae",
      "Lupus",
      "Luyten",
      "Lyra",
      "Mensa",
      "Mensae",
      "Monocerus",
      "Orion",
      "Pavol",
      "Pi Mensae",
      "Pictor",
      "Puppis",
      "Raleigh",
      "Reticulum",
      "Regulus",
      "Rho",
      "Rose",
      "Rouse",
      "Sagittarius",
      "Scorpius",
      "Serpens",
      "Sextan",
      "Spica",
      "Tau Geminorum",
      "Triangulum",
      "Tucana",
      "Tyson",
      "Upsilon",
      "Andromedae",
      "Ursa",
      "Ursae Majoris",
      "Vela",
      "Virgo",
      "Wasp",
      "Procyon",
      "Vorach",
      "Vorash",
      "Tobin",
      "Adara",
      "Doranda",
      "Herschel",
      "Huygens",
      "Canonis",
      "Samos",
      "Laplace",
      "Bell",
      "Penzias",
      "Payne",
      "Rees",
      "Burbidge",
      "Flamsteed",
      "Couper",
      "Marsden",
      "Gill",
      "Chandra",
      "Chanis",
      "Chung",
      "Narlikar",
      "Gupta",
      "Somayaji",
      "Bappu",
      "Ball",
      "Saha",
      "Das Gupta",
      "Lalla",
      "Jani",
      "Natarajan",
      "Fairall",
      "Knox",
      "Weiss",
      "Wilker",
      "Evans",
      "Dilhan",
      "Eryurt",
    ],
    [
      "Expanse",
      "Expanse",
      "Expanse",
      "Nebula",
      "Nebula",
      "Stellar Cumulus",
      "Passage",
      "Pass",
      "Space",
      "Sector",
      "Sector",
      "Sector",
      "Zone",
      "Zone",
      "Region",
      "Region",
      "Quadrant",
      "Quadrant",
      "Territory",
      "Belt",
      "Field",
      "Section",
      "Vicinity",
      "Proximity",
      "Cluster",
      "Cluster",
      "Spiral",
      "Halo Zone",
      "Coronal Stream",
      "Pulsar System",
      "Cloud Node",
      "Supercluster",
      "Vortex",
      "Star System",
      "Cluster System",
      Math.floor(Math.random() * 350) + " System",
    ],
  ],
  "oracle-sector-details-result": [
    [
      "Settled Sector with ",
      "Settled Sector with ",
      "Settled Sector with ",
      "Isolated Sector with ",
      "Isolated Sector with ",
      "Isolated Sector with ",
      "Populated Sector with ",
      "Deserted Sector with ",
      "Uninhabited Sector with ",
    ],
    [
      "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15",
    ],
    [
      "Star systems and ",
    ],
    [
      "no Hyperspace-lanes close-by",
      "no Hyperspace-lanes close-by",
      "no Hyperspace-lanes close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "1 Hyperspace-lane close-by",
      "2 Hyperspace-lanes close-by",
      "2 Hyperspace-lanes close-by",
      "3 Hyperspace-lanes close-by",
    ],
  ],

  "oracle-starsystem-details-result": [
    [
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Single Star System,",
      "Binary Star System,",
      "Binary Star System,",
      "Binary Star System,",
      "Trinary Star System,",
    ],
    [
      "2", "3", "4", "5", "6", "7", "8", "9",
    ],
    [
      "Rocky <a href=\"/oracles/planet-oracles\">Planets</a>, ",
    ],
    [
      "2", "3", "4", "5",
    ],
    [
      "Gas Giants and",
    ],
    [
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "an Asteroid Belt",
      "a Nebula-like gas cloud",
      "a Nebula-like gas cloud",
      "a Nebula-like gas cloud",
      "a Deep-space station",
      "a Deep-space station",
      "a cluster of space-habitats",
    ],
  ],

  "oracle-settlement-name-result": [
    "Aegis",
    "Altair",
    "Altura",
    "Amity",
    "Apex",
    "Apogee",
    "Argosy",
    "Astra",
    "Aurora",
    "Beacon",
    "Brink",
    "Bulwark",
    "Burnell",
    "Burrow",
    "Concord",
    "Crux",
    "Deadrock",
    "Deception",
    "Elysium",
    "Enigma",
    "Erebus",
    "Eris",
    "Evenfall",
    "Eventide",
    "Farpoint",
    "Felicity",
    "Florin",
    "Forlorn",
    "Forsaken",
    "Freya",
    "Glimmer",
    "Gloam",
    "Hearth",
    "Helia",
    "Hypatia",
    "Hyperion",
    "Janus",
    "Karma",
    "Kepler",
    "Koshiba",
    "Lagrange",
    "Larissa",
    "Lasthope",
    "Lastport",
    "Legacy",
    "Lodestar",
    "Luminus",
    "Lyra",
    "Marrow",
    "Meridian",
    "Moirai",
    "Mudd",
    "Neoma",
    "Nerio",
    "Nova",
    "Nyx",
    "Osseus",
    "Paradox",
    "Paragon",
    "Paxton",
    "Perchance",
    "Pinnacle",
    "Polaris",
    "Portent",
    "Prism",
    "Providence",
    "Purgatory",
    "Rampart",
    "Ramshackle",
    "Redemption",
    "Redhaven",
    "Relic",
    "Reprise",
    "Reverie",
    "Rhiannon",
    "Rockhome",
    "Rust",
    "Sagan",
    "Sanctity",
    "Selena",
    "Sepulcher",
    "Sigil",
    "Silvana",
    "Sirius",
    "Sisyphus",
    "Solitude",
    "Spire",
    "Starfall",
    "Summit",
    "Tranquility",
    "Tyson",
    "Unity",
    "Utopia",
    "Vega",
    "Vesper",
    "Wayward",
    "Welkin",
    "Wellspring",
    "Weyland",
    "Wreck",
    "Miasmis", 
    "Dredge", 
    "Rikajima", 
    "Nautisgrad", 
    "Kakoyama", 
    "The Singularity", 
    "Kikkidon", 
    "Harmonil", 
    "Bolham", 
    "Discori", 
    "The Pulpit", 
    "Kōjōta", 
    "Nebula", 
    "Honorsgrad", 
    "Sensōtani", 
    "The Hermitage", 
    "Harmonil", 
    "Icestadt", 
    "Surpril", 
    "Nautilus", 
    "Shintengoku", 
    "Ravenstein", 
    "Primos", 
    "Urutorashi", 
    "Arastok", 
    "Generos", 
    "Arender", 
    "Honpidor", 
    "Iodeen", 
    "Angellis", 
    "Curclick", 
    "Hikmouth", 
    "Shinteng", 
    "The Depths", 
    "Ventios", 
    "Arca", 
    "Materbourne", 
  ],

  "oracle-settlement-firstlook-result": [
    "Beautiful architecture",
    "Built from organic materials",
    "Built from random scrap",
    "Built within repurposed ship",
    "Built within terrain or asteroid",
    "Defensible location",
    "Elevated or multi-level construction",
    "Hidden or subsurface location",
    "High-tech construction",
    "Industrial architecture",
    "Intimidating defenses",
    "Moving or transforming",
    "Obvious social stratification",
    "Precarious location",
    "Rustic architecture",
    "Significant structural damage",
    "Sprawling or dispersed structures",
    "Temporary or seasonal location",
    "Toxic or polluted habitat",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-settlement-initialattitude-result": [
    "Welcoming",
    "Welcoming",
    "Welcoming",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Wary",
    "Wary",
    "Wary",
    "Uncooperative",
    "Hostile",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "In battle",
    "Captured",
    "Unresponsive",
    "Destroyed",
  ],

  "oracle-settlement-authority-result": [
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "Ineffectual",
    "Tolerant",
    "Tolerant",
    "Tolerant",
    "Fair",
    "Fair",
    "Fair",
    "Unyielding",
    "Corrupt",
    "Oppressive",
    "Oppressive",
  ],

  "oracle-settlement-projects-result": [
    "Agriculture",
    "Archeology",
    "Automation",
    "Black market",
    "Command",
    "Defense",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmentalism",
    "Evacuation",
    "Expansion",
    "Exploration",
    "Festival",
    "History",
    "Hunting",
    "Manufacturing",
    "Medical",
    "Migration",
    "Mining",
    "Pacifism",
    "Raiding",
    "Research",
    "Salvage",
    "Secrecy",
    "Shipbuilding",
    "Spirituality",
    "Subsistence",
    "Surveillance",
    "Terraforming",
    "Trade",
    "Warfare",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-settlement-trouble-result": [
    "Battle for leadership",
    "Betrayal from within",
    "Caught in the crossfire",
    "Changing environment",
    "Clash of cultures",
    "Dangerous discovery",
    "Depleted supplies",
    "Deprived of a resource",
    "Failing technology",
    "Feuding factions",
    "Ghostly visitations",
    "Hazardous environment",
    "Hostile lifeforms",
    "Impassable route",
    "Impending attack",
    "Impending natural disaster",
    "Invasive organisms",
    "Mounting debt",
    "Mysterious deaths",
    "Overdue delivery",
    "Plagued by sickness",
    "Preyed upon by raiders",
    "Revolt against leadership",
    "Sabotaged technology",
    "Shunned by others",
    "Social strife",
    "Someone is ill or injured",
    "Someone is missing",
    "Stolen technology or object",
    "Strange phenomenon",
    "Toxic waste or pollution",
    "Volatile energy source",
    "Vulnerable lifeforms",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-spaceborne-peril-result": [
    "Artificial gravity generator malfunctions",
    "Automated defenses or mines protect this area",
    "Compartment catches fire or is breached",
    "Contagion or illness threatens to take hold",
    "Dust clouds imperil navigation or conceal foes",
    "Energy storm looms",
    "Familiar foe appears or sends an ominous message",
    "Gravity well or vortex takes hold",
    "Imperiled ship calls for help",
    "Important device fails or malfunctions",
    "Infestation is revealed",
    "Intruder or stowaway creates trouble",
    "Isolation or fear presses in",
    "Life support system malfunctions",
    "Meteoroid storm fills the sky",
    "Mysterious wreckage portends a new threat",
    "Nearby settlement calls for help",
    "Old repair or patch fails",
    "Onboard dispute or inner turmoil causes a disruption",
    "Others obstruct your path or form a blockade",
    "Phantom signals suggest a lurking foe",
    "Pirates hunt for prey",
    "Power fails",
    "Primary drive or generator malfunctions",
    "Sabotage is revealed",
    "Shockwave or gravity wave approaches",
    "Someone questions your presence here",
    "Stellar anomaly emits hazardous energies",
    "Threatening lifeform draws near",
    "Troubling visions or apparitions",
    "True nature of a cargo, occupant, or passenger is revealed",
    "Unsettling sounds or disturbances",
  ],

  "oracle-spaceborne-opportunity-result": [
    "Advance warning of an environmental threat",
    "Automated signal offers a helpful message or warning",
    "Cache of cargo or supplies",
    "Chance for fellowship or a moment of inner peace",
    "Clear path through otherwise perilous space",
    "Clue offers insight into a current quest or mystery",
    "Clue to a lifeform's nature or vulnerabilities",
    "Derelict ripe for the picking",
    "Foe inadvertently reveals themselves or tips their hand",
    "Friendly interaction with a benign lifeform",
    "Friendly settlement in range",
    "Friendly spacers at work here",
    "Friendly starship crosses your path",
    "Helpful or encouraging message from an acquaintance",
    "Impressive vista offers comfort or inspiration",
    "Interesting site offers opportunities for exploration",
    "Mineral or energy resource detected",
    "Navigational or environmental hazard is left behind",
    "Opening to escape or avoid foes",
    "Plea for help from a potential benefactor",
    "Probe or beacon with useful data",
    "Refuge offers a place to hide, plan, or recover",
    "Sensors pinpoint a lurking foe",
    "Sensors reveal helpful or interesting environmental data",
    "Vehicle or equipment performs beyond expectations",
  ],

  "oracle-settlement-location-result": [
    "Orbital",
    "Orbital",
    "Orbital",
    "Deep Space",
    "Deep Space",
    "Deep Space",
    "Deep Space",
    "Deep Space",
    "Attached to other structure (asteroid, Wreckage clump, etc).",
  ],

  "oracle-fleet-type-result": [
    "Local security forces",
    "Local security forces",
    "Local security forces",
    "Local security forces",
    "Battle fleet",
    "Battle fleet",
    "Pirate wing",
    "Pirate wing",
    "Pirate wing",
    "Pirate wing",
    "Raider horde",
    "Raider horde",
    "Salvager hive",
    "Salvager hive",
    "Salvager hive",
    "Settler caravan",
    "Settler caravan",
    "Settler caravan",
    "Trade caravan",
    "Trade caravan",
    "Trade caravan",
    "Trade caravan",
    "Trade caravan",
    "Transport and escorts",
    "Transport and escorts",
    "Transport and escorts",
  ],

  "oracle-known-starship-result": [
    "<a href=\"https://starwars.fandom.com/wiki/J-type_327_Nubian_starship\" target=\"_blank\">J-type 327 Nubian starship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/1550-LEX_yacht\" target=\"_blank\">1550-LEX yacht</a>",
    "<a href=\"https://starwars.fandom.com/wiki/49AX3\" target=\"_blank\">49AX3 heavy cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/690_light_freighter\" target=\"_blank\">690 light freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/A-Z-Z-3_Light_Freighter\" target=\"_blank\">A-Z-Z-3 Light Freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Abecederian_line\" target=\"_blank\">Abecederian line</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Resurgent-class_Star_Destroyer\" target=\"_blank\">Resurgent-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Acclamator_II-class_Assault_Ship\" target=\"_blank\">Acclamator II-class Assault Ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Acclamator-class_transgalactic_military_assault_ship\" target=\"_blank\">Acclamator-class transgalactic military assault ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Action_IV_transport\" target=\"_blank\">Action IV transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Action_VI_bulk_freighter\" target=\"_blank\">Action VI bulk freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Corona-class_armed_frigate\" target=\"_blank\">Corona-class armed frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/AD-1S_Modular_Multi-Role_Starfighter\" target=\"_blank\">AD-1S Modular Multi-Role Starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Advanced_Agr\" target=\"_blank\">Advanced Agr</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Agr_(starfighter)\" target=\"_blank\">Agr Starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Advanced_Geonosian_Fighter\" target=\"_blank\">Advanced Geonosian Fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nantex-class_territorial_defense_starfighter\" target=\"_blank\">Nantex-class territorial defense starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/YG-4210\" target=\"_blank\">YG-4210 freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Immobilizer_418_cruiser\" target=\"_blank\">Immobilizer 418 cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Imperial_I-class_Star_Destroyer\" target=\"_blank\">Imperial I-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Imperial_II-class_Star_Destroyer\" target=\"_blank\">Imperial II-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Aggressor-class_Assault_Fighter\" target=\"_blank\">Aggressor-class Assault Fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Tartan-class_patrol_cruiser\" target=\"_blank\">Tartan-class patrol cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Venator-class_Star_Destroyer\" target=\"_blank\">Venator-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Delta-7B_Aethersprite-class_light_interceptor\" target=\"_blank\">Delta-7B Aethersprite-class light interceptor</a>",
    "<a href=\"https://starwars.fandom.com/wiki/YV-865_Aurore-class_freighter\" target=\"_blank\">YV-865 Aurore-class freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Alderaanian_diplomatic_cruiser\" target=\"_blank\">Alderaanian diplomatic cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Valor-class_cruiser\" target=\"_blank\">Valor-class cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Broadside-class_cruiser_kdb-1\" target=\"_blank\">Broadside-class cruiser kdb-1</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Alpha-class_Xg-1_Star_Wing\" target=\"_blank\">Alpha-class Xg-1 Star Wing</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Alzarian_warship\" target=\"_blank\">Alzarian warship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/EF76_Nebulon-B_escort_frigate\" target=\"_blank\">EF76 Nebulon-B escort frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nebulon-C_escort_frigate\" target=\"_blank\">Nebulon-C escort frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lambda-class_T-4a_shuttle\" target=\"_blank\">Lambda-class T-4a shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/AO-2_Cometstrike-class_orbital_assault_pod\" target=\"_blank\">AO-2 Cometstrike-class orbital assault pod</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Star_Galleon-class_frigate\" target=\"_blank\">Star Galleon-class frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CR92a_Assassin-class_corvette\" target=\"_blank\">CR92a Assassin-class corvette</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nebulon-B2_frigate\" target=\"_blank\">Nebulon-B2 frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/MC95_Star_Cruiser\" target=\"_blank\">MC95 Star Cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/MC40a_light_cruiser\" target=\"_blank\">MC40a light cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/MC80_Liberty_type_Star_Cruiser\" target=\"_blank\">MC80 Liberty type Star Cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Bellicose-class_heavy_lifter\" target=\"_blank\">Bellicose-class heavy lifter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Personal_Luxury_Yacht_3000\" target=\"_blank\">Personal Luxury Yacht 3000</a>",
    "<a href=\"https://starwars.fandom.com/wiki/MC-18_light_freighter\" target=\"_blank\">MC-18 light freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Assault_shuttle\" target=\"_blank\">Assault shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gamma-class_ATR-6_assault_transport\" target=\"_blank\">Gamma-class ATR-6 assault transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Asteroid_Prospector_AP-300\" target=\"_blank\">Asteroid Prospector AP-300</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Astrogator-class_probe_ship\" target=\"_blank\">Astrogator-class probe ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Zuraco_Cargo_Hauler\" target=\"_blank\">Zuraco Cargo Hauler</a>",
    "<a href=\"https://starwars.fandom.com/wiki/MC80A_Home_One_Type_Heavy_Star_Cruiser\" target=\"_blank\">MC80A Home One Type Heavy Star Cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Longbeam_cruiser\" target=\"_blank\">Longbeam cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Luxury_liner\" target=\"_blank\">Luxury liner</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Strike-class_medium_cruiser\" target=\"_blank\">Strike-class medium cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/B-12_Bacta_Transport\" target=\"_blank\">B-12 Bacta Transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/B-7_light_freighter\" target=\"_blank\">B-7 light freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/B-Wing_Fighter\" target=\"_blank\">B-Wing Fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/A/SF-01_B-wing_starfighter\" target=\"_blank\">A/SF-01 B-wing starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/A/B28_Extinction-class_bomber\" target=\"_blank\">B28 Extinction-class bomber</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Low_Altitude_Assault_Transport/infantry\" target=\"_blank\">Low Altitude Assault Transport/infantry</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CR90_corvette\" target=\"_blank\">CR90 corvette</a>",
    "<a href=\"https://starwars.fandom.com/wiki/T-65B_X-wing_starfighter\" target=\"_blank\">T-65B X-wing starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Munificent-class_star_frigate\" target=\"_blank\">Munificent-class star frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lancer-class_pursuit_craft\" target=\"_blank\">Lancer-class pursuit craft</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Barloz-class_freighter\" target=\"_blank\">Barloz-class freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/YT-1000_light_freighter\" target=\"_blank\">YT-1000 light freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lucrehulk-class_Battleship\" target=\"_blank\">Lucrehulk-class Battleship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Container_transport\" target=\"_blank\">Container transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Belarus-class_medium_cruiser\" target=\"_blank\">Belarus-class medium cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Belbullab-22_heavy_starfighter\" target=\"_blank\">Belbullab-22 heavy starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Belbullab-24_strike_bomber\" target=\"_blank\">Belbullab-24 strike bomber</a>",
    "<a href=\"https://starwars.fandom.com/wiki/YT-1300_light_freighter\" target=\"_blank\">YT-1300 light freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/WTK-85A_interstellar_transport\" target=\"_blank\">WTK-85A interstellar transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/BFF-1_bulk_freighter\" target=\"_blank\">BFF-1 bulk freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Interdictor-class\" target=\"_blank\">Interdictor-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/TIE/ln_space_superiority_starfighter\" target=\"_blank\">TIE/ln space superiority starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Black_Hole-class_Salvage_Dreadnought\" target=\"_blank\">Black Hole-class Salvage Dreadnought</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Field_Secured_Container_Vessel\" target=\"_blank\">Field Secured Container Vessel</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Auzituck_anti-slaver_gunship\" target=\"_blank\">Auzituck anti-slaver gunship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gozanti-class_cruiser\" target=\"_blank\">Gozanti-class cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gladiator_I\" target=\"_blank\">Gladiator I</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lancer-class_frigate\" target=\"_blank\">Lancer-class frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Kom%27rk-class_fighter/transport\" target=\"_blank\">Kom'rk-class fighter/transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/BTL-A4_Y-wing_assault_starfighter/bomber\" target=\"_blank\">BTL-A4 Y-wing assault starfighter/bomber</a>",
    "<a href=\"https://starwars.fandom.com/wiki/New_Republic_Correctional_Transport\" target=\"_blank\">New Republic Correctional Transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Bounty_Hunter_Fighter\" target=\"_blank\">Bounty Hunter Fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/N-1_starfighter\" target=\"_blank\">N-1 starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/C-ROC_Gozanti-class_light_cruiser\" target=\"_blank\">C-ROC Gozanti-class light cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Arquitens-class_command_cruiser\" target=\"_blank\">Arquitens-class command cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Bulk_freighter\" target=\"_blank\">Bulk freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/C-3_passenger_liner\" target=\"_blank\">C-3 passenger liner</a>",
    "<a href=\"https://starwars.fandom.com/wiki/C-9979_landing_craft\" target=\"_blank\">C-9979 landing craft</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Caisson-class_engineering_troop_carrier\" target=\"_blank\">Caisson-class engineering troop carrier</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Calipsan_560_mining_ship\" target=\"_blank\">Calipsan 560 mining ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cargo_ferry\" target=\"_blank\">Cargo ferry</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Class_four_container_transport\" target=\"_blank\">Class four container transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Vakbeor-class_cargo_frigate\" target=\"_blank\">Vakbeor-class cargo frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Intersystem_Transport_Ship\" target=\"_blank\">Intersystem Transport Ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Quasar_Fire-class_cruiser-carrier\" target=\"_blank\">Quasar Fire-class cruiser-carrier</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lancer-class_frigate\" target=\"_blank\">Lancer-class frigate</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Chiss_heavy_cruiser\" target=\"_blank\">Chiss heavy cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CIS-Advanced_starfighter\" target=\"_blank\">CIS-Advanced starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Class_A_modular_freight_transport\" target=\"_blank\">Class A modular freight transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Clone_impound_vessel\" target=\"_blank\">Clone impound vessel</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cloudship\" target=\"_blank\">Cloudship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/MG-100_StarFortress_SF-17\" target=\"_blank\">MG-100 StarFortress SF-17</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Providence-class_carrier/destroyer\" target=\"_blank\">Providence-class carrier/destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/BTA-NR2_Y-wing_starfighter\" target=\"_blank\">BTA-NR2 Y-wing starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Star_Tours_Speeder\" target=\"_blank\">Star Tours Speeder</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Maxillipede_shuttle\" target=\"_blank\">Maxillipede shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sphyrna-class_Hammerhead_corvette\" target=\"_blank\">Sphyrna-class Hammerhead corvette</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Consular-class_space_cruiser\" target=\"_blank\">Consular-class space cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Core_Galaxy_Systems_Dreadnaught\" target=\"_blank\">Core Galaxy Systems Dreadnaught</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nau%27ur-class_yacht\" target=\"_blank\">Nau'ur-class yacht</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Victory_I-class_Star_Destroyer\" target=\"_blank\">Victory I-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Coruscant_Freighter\" target=\"_blank\">Coruscant Freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cosinga-class_Heavy_Corvette\" target=\"_blank\">Cosinga-class Heavy Corvette</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sheathipede-class_Type_B_shuttle\" target=\"_blank\">Sheathipede-class Type B shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CR25_troop_carrier\" target=\"_blank\">CR25 troop carrier</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CR70_corvette\" target=\"_blank\">CR70 corvette</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Z-95_Headhunter\" target=\"_blank\">Z-95 Headhunter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CT-900_freighter\" target=\"_blank\">CT-900 freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Corsair_(ship_type)\" target=\"_blank\">Corsair warship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/CX-5011_PeopleMover\" target=\"_blank\">CX-5011 PeopleMover</a>",
    "<a href=\"https://starwars.fandom.com/wiki/R-41_Starchaser\" target=\"_blank\">R-41 Starchaser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/D-85_freighter\" target=\"_blank\">D-85 freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nu-class_attack_shuttle\" target=\"_blank\">Nu-class attack shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Rho-class_transport_shuttle\" target=\"_blank\">Rho-class transport shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/D-wing_fighter\" target=\"_blank\">D-wing fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Daimanate_starfighter\" target=\"_blank\">Daimanate starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/War_Cruiser\" target=\"_blank\">War Cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Lucrehulk-class_battleship\" target=\"_blank\">Lucrehulk-class battleship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Droid_tri-fighter\" target=\"_blank\">Droid tri-fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/VT-49_Decimator\" target=\"_blank\">VT-49 Decimator</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Deep_Space_Recovery_Vessel_L-2783\" target=\"_blank\">Deep Space Recovery Vessel L-2783</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Mon_Calamari_Star_Cruiser\" target=\"_blank\">Mon Calamari Star Cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Delta-class_T-3c_shuttle\" target=\"_blank\">Delta-class T-3c shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Delta-series_fighter\" target=\"_blank\">Delta-series fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gladiator-class_Star_Destroyer\" target=\"_blank\">Gladiator-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Dimel_assault_ship\" target=\"_blank\">Dimel assault ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Discril-class_attack_cruiser\" target=\"_blank\">Discril-class attack cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Starwind-class_pleasure_yacht\" target=\"_blank\">Starwind-class pleasure yacht</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Providence-class_Dreadnought\" target=\"_blank\">Providence-class Dreadnought</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Star_Courier\" target=\"_blank\">Star Courier</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Colony_ship\" target=\"_blank\">Colony ship</a>",
    "<a href=\"https://starwars.fandom.com/wiki/X-wing_starfighter\" target=\"_blank\">X-wing starfighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nebula-class_Star_Destroyer\" target=\"_blank\">Nebula-class Star Destroyer</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Durosian_fighter\" target=\"_blank\">Durosian fighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/GR-75_medium_transport\" target=\"_blank\">GR-75 medium transport</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Dynamic-class_freighter\" target=\"_blank\">Dynamic-class freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/E-2T_medical_shuttle\" target=\"_blank\">E-2T medical shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Eclipse-class_dreadnought\" target=\"_blank\">Eclipse-class dreadnought</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Edgehawk-Class_Swoop_Carrier\" target=\"_blank\">Edgehawk-Class Swoop Carrier</a>",
    "<a href=\"https://starwars.fandom.com/wiki/EE-730\" target=\"_blank\">EE-730</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Eiram_medical_cruiser\" target=\"_blank\">Eiram medical cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Eliall-class_Cargo_Barge\" target=\"_blank\">Eliall-class Cargo Barge</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Elite-class_vessel\" target=\"_blank\">Elite-class vessel</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Delta-class_JV-7_escort_shuttle\" target=\"_blank\">Delta-class JV-7 escort shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/EML_850_light_freighter\" target=\"_blank\">EML 850 light freighter</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Fury-class_Imperial_interceptor\" target=\"_blank\">Fury-class Imperial interceptor</a>",
    "<a href=\"https://starwars.fandom.com/wiki/IGV-55_surveillance_vessel\" target=\"_blank\">IGV-55 surveillance vessel</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Pursuit-class_light_cruiser\" target=\"_blank\">Pursuit-class light cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Eta-class_shuttle\" target=\"_blank\">Eta-class shuttle</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Imperial_Gozanti-class_cruiser\" target=\"_blank\">Imperial Gozanti-class cruiser</a>",
    "<a href=\"https://starwars.fandom.com/wiki/YV-666_light_freighter\" target=\"_blank\">YV-666 light freighter</a>",
  ],

  "oracle-starship-type-result": [
    "Carrier (Launches fighters)",
    "Corvette (Light attack ship)",
    "Courier (Fast transport)",
    "Courier (Fast transport)",
    "Courier (Fast transport)",
    "Courier (Fast transport)",
    "Cruiser (Medium attack ship)",
    "Cruiser (Medium attack ship)",
    "Cruiser (Medium attack ship)",
    "Dreadnought (Heavy attack ship)",
    "Dreadnought (Heavy attack ship)",
    "Escape pod (Survival craft)",
    "Foundry (Mobile construction platform)",
    "Harvester (Fuel or energy excavator)",
    "Harvester (Fuel or energy excavator)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hauler (Heavy transport)",
    "Hunter (Stealthy attack ship)",
    "Habitat (Mobile dwelling vessel)",
    "Mender (Utility or repair)",
    "Mender (Utility or repair)",
    "Outbounder (Remote survey or research)",
    "Outbounder (Remote survey or research)",
    "Capital ship (Command flagship)",
    "Capital ship (Command flagship)",
    "Battlecruiser (warship)",
    "Battlecruiser (warship)",
    "Prospector (Mineral excavator)",
    "Prospector (Mineral excavator)",
    "Reclaimer (Salvage or rescue)",
    "Reclaimer (Salvage or rescue)",
    "Shuttle (Short-range transport)",
    "Shuttle (Short-range transport)",
    "Shuttle (Short-range transport)",
    "Snub fighter (Small attack craft)",
    "Snub fighter (Small attack craft)",
    "Snub fighter (Small attack craft)",
  ],

  "oracle-starship-name-result": [
    "Arclight",
    "Argent Arrow",
    "Artemis",
    "Astral Explorer",
    "Atlas",
    "Aurora",
    "Avari’s Wake",
    "Banshee’s Cry",
    "Beowulf",
    "Bloody Jaw",
    "Broken Sword",
    "Buccaneer",
    "Cerelis Nine",
    "Clarion Call",
    "Dawn’s Herald",
    "Dead Reckoning",
    "Drift Runner",
    "Eclipse",
    "Elara Five",
    "Enchantress",
    "Endurance",
    "Excalibur",
    "Eye of the Void",
    "Fall of Icarus",
    "Fallen Light",
    "False Hope",
    "Firebreak",
    "First Light",
    "Forge Flier",
    "Fortune’s Favor",
    "Freya’s Wrath",
    "Ghost",
    "Guiding Star",
    "Hand of Fate",
    "Herald of Doom",
    "Implacable",
    "Implicit",
    "Inferno",
    "Invictus",
    "Iron Cairn",
    "Karena’s Reverie",
    "Kraken",
    "Kuno’s Hammer",
    "Lightline",
    "Lodestar",
    "Long Haul",
    "Lost Fortune",
    "Luminous Sorrow",
    "Manta",
    "Mercy",
    "Mutara",
    "Nebula Prowler",
    "Newton’s Folly",
    "Nightfall",
    "Nomad",
    "Obsidian Trident",
    "Onslaught",
    "Orca",
    "Outward Bound",
    "Phantom",
    "Photon",
    "Poltergeist",
    "Profit Margin",
    "Raven’s Call",
    "Raya’s Promise",
    "Reaper",
    "Reforged Hope",
    "Relentless",
    "Royal Signet",
    "Rubicon",
    "Sareea’s Tribute",
    "Second Chance",
    "Shard of the Sun",
    "Shattered Siege",
    "Shattered Star",
    "Silver Talon",
    "Smoldering Flame",
    "Sovereign Skies",
    "Sparrowhawk",
    "Stardust",
    "Starfall",
    "Stellar Hawk",
    "Stormswept",
    "Sundered Aegis",
    "Sundown",
    "Sureshot",
    "Terminus Clipper",
    "Terrapin",
    "Timber Wolf",
    "Tip of the Spear",
    "Titan",
    "Tormentor",
    "Trithia Six",
    "Ultraviolet",
    "Valora’s Comet",
    "Vengeance",
    "Venture",
    "Vigilant",
    "Voidtreader",
    "Vulture",
  ],

  "oracle-starship-manufacturer-result": [
    "<a href=\"https://starwars.fandom.com/wiki/MandalMotors\" target=\"_blank\">MandalMotors</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Baktoid_Armor_Workshop\" target=\"_blank\">Baktoid Armor Workshop</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Corellian_Engineering_Corporation\" target=\"_blank\">Corellian Engineering Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Loronar_Corporation\" target=\"_blank\">Loronar Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Nubia_Star_Drives,_Incorporated\" target=\"_blank\">Nubia Star Drives, Incorporated</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Core_Galaxy_Systems\" target=\"_blank\">Core Galaxy Systems</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Corellia_StarDrive\" target=\"_blank\">Corellia StarDrive</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Damorian_Manufacturing_Corporation\" target=\"_blank\">Damorian Manufacturing Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Galentro_Heavy_Works\" target=\"_blank\">Galentro Heavy Works</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gallofree_Yards,_Inc.\" target=\"_blank\">Gallofree Yards, Inc.</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Gwori_Revolutionary_Industries\" target=\"_blank\">Gwori Revolutionary Industries</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Pantolomin_Shipwrights\" target=\"_blank\">Pantolomin Shipwrights</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Ral_Mundi%27s_Starship_Emporium\" target=\"_blank\">Ral Mundi's Starship Emporium</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Rendili_Hyperworks\" target=\"_blank\">Rendili Hyperworks</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Republic_Engineering_Corporation\" target=\"_blank\">Republic Engineering Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sacul_Aerospace\" target=\"_blank\">Sacul Aerospace</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sienar_Design_Systems\" target=\"_blank\">Sienar Design Systems</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Slayn_%26_Korpil\" target=\"_blank\">Slayn & Korpil</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Telgorn_Corporation\" target=\"_blank\">Telgorn Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Theed_Palace_Space_Vessel_Engineering_Corps\" target=\"_blank\">Theed Palace Space Vessel Engineering Corps</a>",
    "<a href=\"https://starwars.fandom.com/wiki/TransGalMeg_Industries_Inc.\" target=\"_blank\">TransGalMeg Industries Inc.</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Ubrikkian_Transports\" target=\"_blank\">Ubrikkian Transports</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Valahari_Shipworks\" target=\"_blank\">Valahari Shipworks</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Valahari_Shipworks\" target=\"_blank\">Valahari Shipworks</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Ghtroc_Industries\" target=\"_blank\">Ghtroc Industries</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Cygnus_Spaceworks\" target=\"_blank\">Cygnus Spaceworks</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sienar_Fleet_Systems\" target=\"_blank\">Sienar_Fleet_Systems</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Republic_Sienar_Systems\" target=\"_blank\">Republic Sienar Systems</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Koensayr_Manufacturing\" target=\"_blank\">Koensayr Manufacturing</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Hoersch-Kessel_Drive,_Inc.\" target=\"_blank\">Hoersch-Kessel Drive, Inc.</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Mon_Calamari_Shipyards\" target=\"_blank\">Mon Calamari Shipyards</a>",
    "<a href=\"https://starwars.fandom.com/wiki/KonGar_Ship_Works\" target=\"_blank\">KonGar Ship Works</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Kuat_Drive_Yards\" target=\"_blank\">Kuat Drive Yards</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Incom_Corporation\" target=\"_blank\">Incom Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Feethan_Ottraw_Scalable_Assemblies\" target=\"_blank\">Feethan Ottraw Scalable Assemblies</a>",
    "<a href=\"https://starwars.fandom.com/wiki/Sublights_Products_Corporation\" target=\"_blank\">Sublights Products Corporation</a>",
    "<a href=\"https://starwars.fandom.com/wiki/SoroSuub_Corporation\" target=\"_blank\">SoroSuub Corporation</a>",
  ],

  "oracle-starship-initialattitude-result": [
    "Familiar",
    "Friendly",
    "Friendly",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Wary",
    "Wary",
    "Wary",
    "Wary",
    "Wary",
    "Wary",
    "Dismissive",
    "Dismissive",
    "Uncooperative",
    "Uncooperative",
    "Hostile",
    "Hostile",
    "Hostile",
    "Hostile",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "In battle",
    "Unresponsive",
    "Destroyed",
  ],

  "oracle-starship-firstlook-result": [
    "Abnormal sensor readings",
    "Brightly painted",
    "Bristling with weapons",
    "Dark or stealthy",
    "Heavy armor",
    "Immobile",
    "Intimidating profile",
    "Large sensor arrays",
    "Leaking radiation",
    "Low-profile or disguised",
    "Modern or advanced design",
    "Obsolete design",
    "Obvious damage",
    "Biological components",
    "Ornate markings",
    "Oversized engines",
    "Prominent guild emblem",
    "Refitted or repurposed hull",
    "Scarred hull",
    "Built from scrap",
    "Towing or linked",
  ],

  "oracle-starship-mission-result": [
    "Blockade a location",
    "Break a blockade",
    "Collect a resource",
    "Command others",
    "Conduct diplomacy",
    "Conduct espionage",
    "Conduct piracy",
    "Conduct research",
    "Defend against an attack",
    "Deliver messages or data",
    "Establish a settlement",
    "Evacuate a location",
    "Explore a region",
    "Hold prisoners",
    "Hunt down another ship",
    "Launch an attack",
    "Patrol an area",
    "Provide medical aid",
    "Provide repairs",
    "Provide shelter",
    "Quarantine a danger",
    "Raid a settlement",
    "Resupply a settlement",
    "Retrieve salvage",
    "Search and rescue",
    "Smuggle cargo",
    "Survey a site",
    "Test a technology",
    "Transport cargo",
    "Transport passengers",
  ],

  "oracle-derelict-location-result": [
    "Planetside",
    "Orbital",
    "Deep Space",
  ],

  "oracle-derelict-type-result": [
    "Spaceship (adrift or crashed)",
    "Settlement (or space station)",
  ],

  "oracle-derelict-condition-result": [
    "Functional",
    "Limited power",
    "Cold and dark",
    "Damaged or breached",
    "Heavily damaged",
    "Impending destruction",
  ],

  "oracle-derelict-outer-first-look-result": [
    "Blocked access",
    "Corpses",
    "Hazardous readings",
    "Mutated structure",
    "Odd orientation",
    "Overgrown or entangled",
    "Sending a signal or message",
    "Signs that others are here",
    "Stripped exterior",
    "Time or reality distortions",
  ],

  "oracle-derelict-inner-first-look-result": [
    "Abnormal gravity",
    "Active bots",
    "Archaic equipment",
    "Automated announcements",
    "Biological infestation",
    "Charred surfaces",
    "Claw marks",
    "Cluttered with debris",
    "Corroded surfaces",
    "Cramped spaces",
    "Creaking hull",
    "Esoteric writing or symbols",
    "Evidence of new inhabitants",
    "Exposed wiring or conduits",
    "Flashing strobe lights",
    "Fluctuating power",
    "Haunting visions of the dead",
    "Hazardous temperature",
    "Heavy steam or moisture",
    "Littered with corpses",
    "Nesting or feeding creatures",
    "Ornate furnishings",
    "Scarred by gunfire",
    "Sealed against intruders",
    "Signs of looting or scavenging",
    "Smell of decay",
    "Splattered with blood",
    "Temporal distortions",
    "Thick haze or smoke",
    "Unstable energy surges",
    "Watchful AI",
  ],

  "oracle-derelict-zone-type-result": [
    "<a href=\"/oracles/space-oracles#derelict-zone-access\">Access</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-community\">Community</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-engineering\">Engineering</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-living\">Living</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-medical\">Medical</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-operations\">Operations</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-production\">Production</a>",
    "<a href=\"/oracles/space-oracles#derelict-zone-research\">Research</a>",
  ],

  "oracle-derelict-zone-access-area-result": [
    "Corridor",
    "Stairs",
    "Lift or elevator",
    "Catwalk or bridge",
    "Vertical shaft or ladder",
    "Hub or intersection",
    "Crawl space or duct",
    "Airlock or external",
  ],
  "oracle-derelict-zone-access-feature-result": [
    "Abandoned gear", 
    "Blood trail", 
    "Breached door or hatch", 
    "Control or terminal station", 
    "Corpse", 
    "Dismantled equipment", 
    "Flashing strobes", 
    "Leaking pipes", 
    "Makeshift barricade", 
    "Opened or missing panels", 
    "Organic growths", 
    "Ruined bot", 
    "Scrawled warning", 
    "Sealed breach", 
    "Sounds of movement", 
    "Steam or smoke", 
    "Wandering bot", 
    "Windows or viewports", 
    "Wrecked passage or debris", 
  ],
  "oracle-derelict-zone-access-peril-result": [
    "Alarm or failsafe is triggered", 
    "Automated defenses", 
    "Blocked or sealed path", 
    "Dreadful scene of death or violence", 
    "Foe closes in", 
    "Gear is failing or broken", 
    "Hazardous environmental change", 
    "Path is trapped", 
    "Unsettling sound or disturbance", 
  ],
  "oracle-derelict-zone-access-opportunity-result": [
    "Directions, shortcut, or alternate path", 
    "Encounter with a friendly survivor, explorer, or denizen", 
    "Hopeful signs of life", 
    "Opening to outmaneuver or escape a threat or foe", 
    "Useful equipment", 
  ],

  "oracle-derelict-zone-community-area-result": [
    "Bar or club", 
    "Classroom or education", 
    "Concourse or hub", 
    "Entertainment", 
    "Gym or fitness", 
    "Market or trade", 
    "Park or garden", 
    "Promenade or overlook", 
    "Restaurant or dining", 
    "Temple or chapel", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-community-feature-result": [
    "Ad-hoc memorials", 
    "Art depicting historic event", 
    "Artificial environment", 
    "Automated announcements", 
    "Barricaded area", 
    "Gaming devices or interfaces", 
    "Graffiti or vandalization", 
    "Guard post or surveillance", 
    "Mass grave or corpses", 
    "Panoramic viewport", 
    "Rubble or debris", 
  ],
  "oracle-derelict-zone-community-peril-result": [
    "Biological infestation", 
    "Breached or broken structure", 
    "Distressing signs of mass violence or death", 
    "Flooded environment", 
    "Foe lurks within concealment", 
    "Fragile structural integrity", 
    "Haunting vision of life here before the fall", 
    "Hazardous environmental change", 
    "Heartbreaking memento of lost lives", 
  ],
  "oracle-derelict-zone-community-opportunity-result": [
    "Culturally significant object or artifact", 
    "Salvageable goods or resources", 
    "Secure area offers a moment of peace", 
    "Terminal with access to site details", 
    "Valuable item", 
  ],

  "oracle-derelict-zone-engineering-area-result": [
    "Control room", 
    "Engine room or power core", 
    "Engineering offices", 
    "Equipment storage", 
    "Fuel or coolant tanks", 
    "Life support", 
    "Maintenance tube", 
    "Vehicle bay or garage", 
    "Water processing", 
    "Workshop", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-engineering-feature-result": [
    "Cluttered workbench", 
    "Control terminal", 
    "Crane or lift", 
    "Disassembled equipment", 
    "Flickering status monitors", 
    "Jury-rigged equipment", 
    "Multilevel layout", 
    "Pipes and valves", 
    "Sharp ozone smell", 
    "Unfinished project", 
    "Utility bots", 
  ],
  "oracle-derelict-zone-engineering-peril-result": [
    "Corrosive leak", 
    "Erratic utility bots", 
    "Failing equipment requires a specific part or skill", 
    "Fire or energy surge", 
    "Precarious or broken path", 
    "Radioactive hotspot", 
    "Sabotaged equipment", 
    "Shrouded atmosphere conceals a lurking foe", 
    "Unstable or failing power core", 
  ],
  "oracle-derelict-zone-engineering-opportunity-result": [
    "Advanced or experimental equipment", 
    "Chance to restore power or function", 
    "Helpful plans or schematics", 
    "Helpful utility bot", 
    "Useful tool or device", 
  ],

  "oracle-derelict-zone-living-area-result": [
    "Food storage", 
    "Galley or kitchen", 
    "Laundry", 
    "Locker room or storage", 
    "Mess hall or dining", 
    "Observation lounge", 
    "Quarters (communal)", 
    "Quarters (individual)", 
    "Restroom or showers", 
    "Sleeping pods", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-living-feature-result": [
    "Abandoned pet", 
    "Audible music", 
    "Cherished personal item", 
    "Failed barricade", 
    "Half-eaten food", 
    "Messages from loved ones", 
    "Ransacked belongings", 
    "Remains of the dead", 
    "Scuttling vermin", 
    "Shrine or altar", 
    "Unusual art", 
  ],
  "oracle-derelict-zone-living-peril-result": [
    "Booby trap", 
    "Distressing written message", 
    "Disturbing evidence of exploitive living conditions", 
    "Dreadful scene of death or violence", 
    "Lured into danger by signs of life", 
    "Recorded message reveals a threat or complication", 
    "Sealed door or hatch blocks access", 
    "Signs of unwelcome invaders", 
    "Unsettling sound or disturbance", 
  ],
  "oracle-derelict-zone-living-opportunity-result": [
    "Culturally significant object or artifact", 
    "Hidden stash of valuable contraband", 
    "Intact barricade or protected area", 
    "Recorded message reveals helpful aspects of this site", 
    "Useful personal gear", 
  ],

  "oracle-derelict-zone-medical-area-result": [
    "Crematorium", 
    "Emergency or triage", 
    "Isolation or containment", 
    "Medical lab", 
    "Medical offices", 
    "Morgue", 
    "Operating room", 
    "Pharmacy or drug locker", 
    "Prosthetics workshop", 
    "Ward or clinic", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-medical-feature-result": [
    "Autopsied corpse", 
    "Biological specimens", 
    "Blood spatter or pools", 
    "Bloody medical supplies", 
    "Broken prosthetics", 
    "Corpse of a healer", 
    "Dissected specimen", 
    "Improvised overflow beds", 
    "Medical monitors", 
    "Medical records or scans", 
    "Stacks of body bags", 
  ],
  "oracle-derelict-zone-medical-peril-result": [
    "Disgusting sight / smell", 
    "Disturbing evidence of medical misconduct", 
    "Erratic medical bots", 
    "Evidence of a virulent disease", 
    "Malfunctioning medical equipment", 
    "Repercussions of a medical experiment", 
    "Restless dead", 
    "Signs of a horrific death", 
    "Signs of broken quarantine", 
  ],
  "oracle-derelict-zone-medical-opportunity-result": [
    "Cache of medicine", 
    "Clues to a medical mystery", 
    "Helpful medical bot", 
    "Unusual or rare specimen", 
    "Useful medical equipment", 
  ],

  "oracle-derelict-zone-operations-area-result": [
    "Admin or command offices", 
    "Armory", 
    "Bridge or command center", 
    "Brig or cells", 
    "Comms center", 
    "Computer core", 
    "Conference or briefing room", 
    "Landing bay or hangar", 
    "Lounge", 
    "Security", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-operations-feature-result": [
    "Automated warning", 
    "Buckled blast doors", 
    "Control terminal", 
    "Emergency lighting", 
    "EV suit storage", 
    "Hissing comms channel", 
    "Intricate control panels", 
    "Map of the site", 
    "Recorded message", 
    "Video surveillance monitors", 
    "Written logs", 
  ],
  "oracle-derelict-zone-operations-peril-result": [
    "Automated defenses target you", 
    "Broken equipment limits control", 
    "Coded message or puzzling security device", 
    "Discouraging evidence of failed plans or defenses", 
    "Displays reveal a new threat elsewhere in this site", 
    "Failing power", 
    "Hostile AI", 
    "Sealed blast doors block access", 
    "Sensors indicate the arrival of an external threat", 
  ],
  "oracle-derelict-zone-operations-opportunity-result": [
    "Cache of weapons or ammo", 
    "Helpful AI", 
    "Keycard or access code", 
    "Log offers insight into this site's downfall", 
    "Secure area offers a moment of peace", 
  ],

  "oracle-derelict-zone-production-area-result": [
    "Airlock or staging area", 
    "Assembly or processing", 
    "Cargo bay", 
    "Equipment storage", 
    "Exosuit bay", 
    "Harvesting or mining platform", 
    "Monitoring or control room", 
    "Processed goods storage", 
    "Raw materials storage", 
    "Scrapyard", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-production-feature-result": [
    "Cargo lifts", 
    "Control panels", 
    "Disassembled machinery", 
    "Elevated walkways", 
    "Environment suits", 
    "Ill-fated workers", 
    "Immense machinery", 
    "Sealed or locked containers", 
    "Tools", 
    "Vats of chemicals or gas", 
    "Written manifest", 
  ],
  "oracle-derelict-zone-production-peril-result": [
    "Claustrophobic spaces", 
    "Dangerous machinery", 
    "Disturbing evidence of exploited labor", 
    "Extreme temperatures", 
    "Hazardous materials", 
    "Impending industrial disaster", 
    "Malfunctioning automation", 
    "Rivals seek to secure these resources", 
    "Signs of an unearthed or manufactured threat", 
  ],
  "oracle-derelict-zone-production-opportunity-result": [
    "Helpful vehicle or transport", 
    "Rare or valuable resource", 
    "Salvageable materials", 
    "Useful equipment", 
    "Valuable cargo", 
  ],

  "oracle-derelict-zone-research-area-result": [
    "Clean room", 
    "Cold storage", 
    "Creature or animal pens", 
    "Decontamination room", 
    "Hazardous material storage", 
    "Hydroponics or agriculture", 
    "Isolation or containment", 
    "Lab", 
    "Library or records", 
    "Secure vault", 
    "Transition into <a href=\"/oracles/space-oracles#derelict-zone-type\">New Zone</a>", 
  ],
  "oracle-derelict-zone-research-feature-result": [
    "Aquarium or tank", 
    "Biological specimens", 
    "Bones or fossils", 
    "Broken equipment", 
    "Cryptic research notes", 
    "Hastily destroyed data", 
    "Hazmat suits", 
    "Inscrutable artifact", 
    "Invasive plant growth", 
    "Recorded research log", 
    "Spilled chemicals", 
  ],
  "oracle-derelict-zone-research-peril-result": [
    "Automated containment protocols are activated", 
    "Biological infestation", 
    "Dangerous specimen", 
    "Disturbing outcome of a failed experiment", 
    "Evidence of sinister experiments", 
    "Fragile vault holds a dire threat", 
    "Signs of broken containment", 
    "Toxic environment", 
    "Unstable technology", 
  ],
  "oracle-derelict-zone-research-opportunity-result": [
    "Helpful research data", 
    "Records of a notable discovery", 
    "Specialized research tools", 
    "Unique prototype", 
    "Useful navigational data", 
  ],
};
export default spaceOracleResults;