const spaceOracleResults = {
  "oracle-space-sighting-result": [
    "<a href=\"/oracles/space-oracles#star\">Star</a>",
    "<a href=\"/oracles/space-oracles#celestial-phenomena\">Celestial Phenomena</a>",
    "<a href=\"/oracles/space-oracles#debris-field\">Debris Field</a>",
    "<a href=\"/oracles/planet-oracles\">Planet</a>",
    "<a href=\"/oracles/space-oracles#space-settlements\">Settlement</a>",
    "<a href=\"/oracles/space-oracles#starships\">Starship</a>",
    "<a href=\"/oracles/space-oracles#derelicts\">Derelict</a>",
    "<a href=\"/oracles/space-oracles#space-creatures\">Creature</a>",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-star-result": [
    "Smoldering Red Star",
    "Smoldering Red Star",
    "Smoldering Red Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Glowing Orange Star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Burning yellow star",
    "Blazing blue star",
    "Blazing blue star",
    "Blazing blue star",
    "White dwarf shining with spectral light",
    "White dwarf shining with spectral light",
    "White dwarf shining with spectral light",
    "Two Red Stars orbiting far from each other",
    "Two Red Stars orbiting far from each other",
    "Two stars in close orbit connected by fiery tendrils of energy",
    "Two stars in close orbit connected by fiery tendrils of energy",
    "Young star incubating in a molecular cloud",
    "Corrupted star radiating with unnatural light",
    "Neutron star surrounded by intense magnetic fields",
    "Hypergiant star generating turbulent solar winds",
    "Artificial star constructed by a long-dead civilization",
    "Unstable star showing signs of impending supernova",

  ],

  "oracle-celestial-phenomena-result": [
    "Large Rogue Asteroid",
    "Comet with a Tail of Ionized Gas",
    "Fiery Energy Storm",
    "Chaotic Meteoroid Storm",
    "Turbulent Gravitational Wave",
    "Dense Nebula Cloud",
    "Small Black Hole",
    "Supermassive Black Hole",
  ],

  "oracle-debris-field-result": [
    "Mineral Asteroids",
    "Frozen Asteroids",
    "Creature boneyard",
    "Metallic Wreckage",
  ],

  "oracle-settlement-result": [
  ],

  "oracle-starship-result": [
  ],

  "oracle-derelict-result": [
  ],

  "oracle-creature-result": [
  ],

  "oracle-known-sector-result": [
    "<a href=\"https://starwars.fandom.com/wiki/Koradin_sector\" target=\"_blank\">Koradin Sector</a>",
  ],

  "oracle-unknown-sector-result": [
    [
      "", "", "", "", "", "", "", "", 
      "Alpha",
      "Beta",
      "Gamma",
      "Ceti",
      "Picon",
      "Delta",
      "Epsilon",
      "Theta",
      "Zeta",
      "Omega",
      "Tau",
      "Nebulon",
      "Far",
      "Deep",
      "Omicron",
      "Sigma",
      "Kappa",
      "Rho",
      "Minor",
      "Major",
      "Greater",
      Math.floor(Math.random() * 300),
    ],
    [
      "Arfell",
      "Aeron",
      "Andromeda",
      "Apius",
      "Aquarius",
      "Ara",
      "Alpha Andromeda",
      "Alpha Centauri",
      "Alpha Persei",
      "Alcor",
      "Algol",
      "Antares",
      "Basri",
      "Behram",
      "Beta Picoris",
      "Boötes",
      "Cancri",
      "Canes Venatici",
      "Canis",
      "Capricorn",
      "Cassiopeia",
      "Castor",
      "Cebus",
      "Centaurus",
      "Ceti",
      "Cetus",
      "Coma Berenices",
      "Corona Borealis",
      "Corot",
      "Cygnus",
      "Cygni",
      "Draco",
      "Eridanus",
      "Eridanus",
      "Fiken",
      "Fornax",
      "Fomalhaut",
      "Gilese",
      "Goddard",
      "Hercules",
      "Herculis",
      "Horologium",
      "Holbrook",
      "Hydra",
      "Hydrus",
      "Leo",
      "Leonis",
      "Libra",
      "Librae",
      "Lupus",
      "Luyten",
      "Lyra",
      "Mensa",
      "Mensae",
      "Monocerus",
      "Orion",
      "Pavol",
      "Pi Mensae",
      "Pictor",
      "Puppis",
      "Raleigh",
      "Reticulum",
      "Regulus",
      "Rho",
      "Rose",
      "Rouse",
      "Sagittarius",
      "Scorpius",
      "Serpens",
      "Sextan",
      "Spica",
      "Tau Geminorum",
      "Triangulum",
      "Tucana",
      "Tyson",
      "Upsilon",
      "Andromedae",
      "Ursa",
      "Ursae Majoris",
      "Vela",
      "Virgo",
      "Wasp",
      "Procyon",
      "Vorach",
      "Vorash",
      "Tobin",
      "Adara",
      "Doranda",
      "Herschel",
      "Huygens",
      "Canonis",
      "Samos",
      "Laplace",
      "Bell",
      "Penzias",
      "Payne",
      "Rees",
      "Burbidge",
      "Flamsteed",
      "Couper",
      "Marsden",
      "Gill",
      "Chandra",
      "Chanis",
      "Chung",
      "Narlikar",
      "Gupta",
      "Somayaji",
      "Bappu",
      "Ball",
      "Saha",
      "Das Gupta",
      "Lalla",
      "Jani",
      "Natarajan",
      "Fairall",
      "Knox",
      "Weiss",
      "Wilker",
      "Evans",
      "Dilhan",
      "Eryurt",
    ],
    [
      "Expanse",
      "Expanse",
      "Expanse",
      "Nebula",
      "Nebula",
      "Stellar Cumulus",
      "Passage",
      "Pass",
      "Space",
      "Sector",
      "Sector",
      "Sector",
      "Zone",
      "Zone",
      "Region",
      "Region",
      "Quadrant",
      "Quadrant",
      "Territory",
      "Belt",
      "Field",
      "Section",
      "Vicinity",
      "Proximity",
      "Cluster",
      "Cluster",
      "Spiral",
      "Halo Zone",
      "Coronal Stream",
      "Pulsar System",
      "Cloud Node",
      "Supercluster",
      "Vortex",
      "Star System",
      "Cluster System",
      Math.floor(Math.random() * 350) + " System",
    ],
  ],

  "oracle-settlement-name-result": [
    "Aegis",
    "Altair",
    "Altura",
    "Amity",
    "Apex",
    "Apogee",
    "Argosy",
    "Astra",
    "Aurora",
    "Beacon",
    "Brink",
    "Bulwark",
    "Burnell",
    "Burrow",
    "Concord",
    "Crux",
    "Deadrock",
    "Deception",
    "Elysium",
    "Enigma",
    "Erebus",
    "Eris",
    "Evenfall",
    "Eventide",
    "Farpoint",
    "Felicity",
    "Florin",
    "Forlorn",
    "Forsaken",
    "Freya",
    "Glimmer",
    "Gloam",
    "Hearth",
    "Helia",
    "Hypatia",
    "Hyperion",
    "Janus",
    "Karma",
    "Kepler",
    "Koshiba",
    "Lagrange",
    "Larissa",
    "Lasthope",
    "Lastport",
    "Legacy",
    "Lodestar",
    "Luminus",
    "Lyra",
    "Marrow",
    "Meridian",
    "Moirai",
    "Mudd",
    "Neoma",
    "Nerio",
    "Nova",
    "Nyx",
    "Osseus",
    "Paradox",
    "Paragon",
    "Paxton",
    "Perchance",
    "Pinnacle",
    "Polaris",
    "Portent",
    "Prism",
    "Providence",
    "Purgatory",
    "Rampart",
    "Ramshackle",
    "Redemption",
    "Redhaven",
    "Relic",
    "Reprise",
    "Reverie",
    "Rhiannon",
    "Rockhome",
    "Rust",
    "Sagan",
    "Sanctity",
    "Selena",
    "Sepulcher",
    "Sigil",
    "Silvana",
    "Sirius",
    "Sisyphus",
    "Solitude",
    "Spire",
    "Starfall",
    "Summit",
    "Tranquility",
    "Tyson",
    "Unity",
    "Utopia",
    "Vega",
    "Vesper",
    "Wayward",
    "Welkin",
    "Wellspring",
    "Weyland",
    "Wreck",
  ],

  "oracle-settlement-firstlook-result": [
    "Beautiful architecture",
    "Built from organic materials",
    "Built from random scrap",
    "Built within repurposed ship",
    "Built within terrain or asteroid",
    "Defensible location",
    "Elevated or multi-level construction",
    "Hidden or subsurface location",
    "High-tech construction",
    "Industrial architecture",
    "Intimidating defenses",
    "Moving or transforming",
    "Obvious social stratification",
    "Precarious location",
    "Rustic architecture",
    "Significant structural damage",
    "Sprawling or dispersed structures",
    "Temporary or seasonal location",
    "Toxic or polluted habitat",
    "<a href=\"/oracles/core-oracles#descriptor\">Descriptor + Focus</a>",
  ],

  "oracle-settlement-initialattitude-result": [
    "Welcoming",
    "Welcoming",
    "Welcoming",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Neutral / automated",
    "Wary",
    "Wary",
    "Wary",
    "Uncooperative",
    "Hostile",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "Asking for help",
    "In battle",
    "Captured",
    "Unresponsive",
    "Destroyed",
  ],

  "oracle-settlement-authority-result": [
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "None / lawless",
    "Ineffectual",
    "Tolerant",
    "Tolerant",
    "Tolerant",
    "Fair",
    "Fair",
    "Fair",
    "Unyielding",
    "Corrupt",
    "Oppressive",
    "Oppressive",
  ],

  "oracle-settlement-projects-result": [
    "Agriculture",
    "Archeology",
    "Automation",
    "Black market",
    "Command",
    "Defense",
    "Energy",
    "Engineering",
    "Entertainment",
    "Environmentalism",
    "Evacuation",
    "Expansion",
    "Exploration",
    "Festival",
    "History",
    "Hunting",
    "Manufacturing",
    "Medical",
    "Migration",
    "Mining",
    "Pacifism",
    "Raiding",
    "Research",
    "Salvage",
    "Secrecy",
    "Shipbuilding",
    "Spirituality",
    "Subsistence",
    "Surveillance",
    "Terraforming",
    "Trade",
    "Warfare",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-settlement-trouble-result": [
    "Battle for leadership",
    "Betrayal from within",
    "Caught in the crossfire",
    "Changing environment",
    "Clash of cultures",
    "Dangerous discovery",
    "Depleted supplies",
    "Deprived of a resource",
    "Failing technology",
    "Feuding factions",
    "Ghostly visitations",
    "Hazardous environment",
    "Hostile lifeforms",
    "Impassable route",
    "Impending attack",
    "Impending natural disaster",
    "Invasive organisms",
    "Mounting debt",
    "Mysterious deaths",
    "Overdue delivery",
    "Plagued by sickness",
    "Preyed upon by raiders",
    "Revolt against leadership",
    "Sabotaged technology",
    "Shunned by others",
    "Social strife",
    "Someone is ill or injured",
    "Someone is missing",
    "Stolen technology or object",
    "Strange phenomenon",
    "Toxic waste or pollution",
    "Volatile energy source",
    "Vulnerable lifeforms",
    "<a href=\"/oracles/core-oracles#action\">Action + Theme</a>",
  ],

  "oracle-spaceborne-peril-result": [
    "Artificial gravity generator malfunctions",
    "Automated defenses or mines protect this area",
    "Compartment catches fire or is breached",
    "Contagion or illness threatens to take hold",
    "Dust clouds imperil navigation or conceal foes",
    "Energy storm looms",
    "Familiar foe appears or sends an ominous message",
    "Gravity well or vortex takes hold",
    "Imperiled ship calls for help",
    "Important device fails or malfunctions",
    "Infestation is revealed",
    "Intruder or stowaway creates trouble",
    "Isolation or fear presses in",
    "Life support system malfunctions",
    "Meteoroid storm fills the sky",
    "Mysterious wreckage portends a new threat",
    "Nearby settlement calls for help",
    "Old repair or patch fails",
    "Onboard dispute or inner turmoil causes a disruption",
    "Others obstruct your path or form a blockade",
    "Phantom signals suggest a lurking foe",
    "Pirates hunt for prey",
    "Power fails",
    "Primary drive or generator malfunctions",
    "Sabotage is revealed",
    "Shockwave or gravity wave approaches",
    "Someone questions your presence here",
    "Stellar anomaly emits hazardous energies",
    "Threatening lifeform draws near",
    "Troubling visions or apparitions",
    "True nature of a cargo, occupant, or passenger is revealed",
    "Unsettling sounds or disturbances",
  ],

  "oracle-spaceborne-opportunity-result": [
    "Advance warning of an environmental threat",
    "Automated signal offers a helpful message or warning",
    "Cache of cargo or supplies",
    "Chance for fellowship or a moment of inner peace",
    "Clear path through otherwise perilous space",
    "Clue offers insight into a current quest or mystery",
    "Clue to a lifeform's nature or vulnerabilities",
    "Derelict ripe for the picking",
    "Foe inadvertently reveals themselves or tips their hand",
    "Friendly interaction with a benign lifeform",
    "Friendly settlement in range",
    "Friendly spacers at work here",
    "Friendly starship crosses your path",
    "Helpful or encouraging message from an acquaintance",
    "Impressive vista offers comfort or inspiration",
    "Interesting site offers opportunities for exploration",
    "Mineral or energy resource detected",
    "Navigational or environmental hazard is left behind",
    "Opening to escape or avoid foes",
    "Plea for help from a potential benefactor",
    "Probe or beacon with useful data",
    "Refuge offers a place to hide, plan, or recover",
    "Sensors pinpoint a lurking foe",
    "Sensors reveal helpful or interesting environmental data",
    "Vehicle or equipment performs beyond expectations",
  ],

  "oracle-settlement-location-result": [
    "Orbital",
    "Orbital",
    "Orbital",
    "Deep Space",
    "Deep Space",
    "Deep Space",
    "Deep Space",
    "Deep Space",
    "Attached to other structure (asteroid, Wreckage clump, etc).",
  ],

};
export default spaceOracleResults;